import {designTerrace,terraceEnProfile,terraceSources} from './terrace-design.js';
import {renderTerracePlan} from './diagram-renderer.js';
const fmt=(n,d=2)=>new Intl.NumberFormat('nb-NO',{maximumFractionDigits:d}).format(n);
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const source='EN 1991-1-1, tabell 6.2, kategori A balkong: øvre EN-eksempel qk=4,0 og Qk=3,0. Norske NA-valg må kontrolleres.';
export function initTerraceUi(root){
 const controls={},form=el('form',undefined,'rib-form terrace-form'),error=el('p',undefined,'rib-error'),resultRoot=el('section',undefined,'rib-report terrace-report');
 let result=null,rowYs=null,supportXs=null,selected=null;
 error.setAttribute('role','alert');resultRoot.setAttribute('aria-live','polite');
 function section(title,help,advanced=false){const box=el(advanced?'details':'fieldset');box.append(el(advanced?'summary':'legend',title),el('p',help,'muted'));const grid=el('div',undefined,'rib-fields');box.append(grid);form.append(box);return grid;}
 function field(grid,id,label,value,options=null,help=''){const wrapper=el('label'),input=el(options?'select':'input');input.id='rib-'+id;input.name=id;input.required=true;if(options){for(const [v,t]of options){const option=el('option',t);option.value=v;input.append(option);}}else {input.type='text';input.inputMode='decimal';input.maxLength=600;}input.value=String(value);wrapper.append(el('span',label),input);if(help)wrapper.append(el('small',help));grid.append(wrapper);controls[id]=input;return input;}
 function tick(grid,id,label){const wrapper=el('label',undefined,'rib-tick'),input=el('input');input.type='checkbox';input.id='rib-'+id;wrapper.append(input,el('span',label));grid.append(wrapper);controls[id]=input;return input;}
 const geometry=section('Terrasse: mål og bæring','Oppgi terrassens mål. Verktøyet beregner bjelkespenn og fordeler dragere og stolper.');
 field(geometry,'terraceLengthM','Lengde langs huset (m)','');field(geometry,'terraceDepthM','Dybde ut fra huset (m)','');field(geometry,'terraceHeightM','Høyde over terreng (m)','');
 field(geometry,'wallSupport','Bæring ved huset','free_standing',[['free_standing','Frittstående – egne stolper på begge sider'],['documented','Dokumentert bæring ved huset']]);
 const members=section('Bjelkelag og dragere','Velg faktiske dimensjoner. En dobbel drager regnes som separate planker.');
 const sections=[98,123,148,173,198,223].map(h=>['48x'+h,'48 × '+h+' mm']).concat([['73x223','73 × 223 mm'],['90x225','90 × 225 mm'],['115x315','115 × 315 mm'],['custom','Annen dimensjon']]);
 for(const [role,label]of [['joist','Terrassebjelke'],['beam','Dragerplanke']]){
  field(members,role+'Section',label+' – dimensjon','48x198',sections);
  field(members,role+'Grade',label+' – styrkeklasse','C24',[['C24','C24 konstruksjonsvirke'],['GL30c','GL30c limtre']]);
  field(members,role+'WidthMm',label+' – bredde (mm)',48);field(members,role+'HeightMm',label+' – høyde (mm)',198);
 }
 field(members,'spacingMm','Bjelkelag c/c (mm)',600,[['400','400 mm'],['600','600 mm'],['750','750 mm'],['800','800 mm'],['1200','1200 mm']]);
 field(members,'beamCount','Antall planker i hver drager',2,[['1','Enkel'],['2','Dobbel'],['3','Tre planker']]);
 tick(members,'equalSharing','Lik lastdeling er dokumentert, og bjelkene ligger oppå alle dragerplankene');
 const build=section('Oppbygning og egenvekt','Egenvekt beregnes fra bordvolum og densitet. Bjelker og dragere legges til én gang i lastveien.',true);
 field(build,'deckThicknessMm','Tykkelse terrassebord (mm)',28,[['21','21 mm'],['28','28 mm'],['34','34 mm']]);field(build,'deckWidthMm','Bredde terrassebord (mm)',120);
 field(build,'deckGapMm','Avstand mellom bord (mm)',6);field(build,'deckDensityKgM3','Densitet terrassebord (kg/m³)',550,null,'550 er en startverdi. Bruk dokumentert densitet og fukttilstand for valgt produkt.');
 field(build,'additionalDeadKnM2','Annen permanent last (kN/m²)',0,null,'Ekstra lag og fast utstyr. Bord, bjelker og dragere er allerede med.');
 const usage=section('Nyttelast og snø','Bruksområdet fyller inn nyttelast og punktlast. Kontroller prosjektets lastkategori og lokale snøforhold.');
 field(usage,'useCase','Bruksområde','residential',[['residential','Boligterrasse / balkong – EN kategori A'],['custom','Annet / prosjektspesifikke laster']]);
 field(usage,'liveKnM2','Nyttelast qk (kN/m²)',4);field(usage,'pointKn','Konsentrert nyttelast Qk (kN)',3,null,'Kontrolleres som alternativ til den fordelte nyttelasten.');
 field(usage,'snowStatus','Snølast på terrassen','unknown',[['unknown','Ikke avklart – vis foreløpig spennberegning'],['documented','Karakteristisk snølast er dokumentert'],['not_applicable','Snølast er ikke aktuell – dokumentert begrunnelse']]);
 field(usage,'snowKnM2','Karakteristisk snølast på terrasse (kN/m²)','',null,'Oppgi last på terrasseflaten. Snølast på bakken og dimensjonerende last kan ikke brukes direkte.');
 field(usage,'snowSource','Snølastkilde / begrunnelse','').inputMode='text';
 const basis=section('Standardgrunnlag og kontrollomfang','EN 1990 kombinasjoner og EN 1995-1-1 medlemskontroll. Norske nasjonale tillegg og utgaver må kontrolleres for prosjektet; forhåndsverdiene er EN-eksempler.',true);
 field(basis,'loadSource','Kilde for nyttelast og punktlast',source).inputMode='text';
 field(basis,'terraceServiceClass','Klimaklasse',3,[['2','2 – beskyttet under tak'],['3','3 – utendørs / fuktig']]);
 field(basis,'terraceLimitRatio','Prosjektets nedbøyningsgrense L/',300);field(basis,'terraceBearingMm','Fysisk oppleggslengde (mm)',90,null,'Ved bjelke på drager begrenses kontaktlengden av dragerens samlede bredde.');
 field(basis,'terraceExpression','ULS-kombinasjonsregel','6.10ab',[['6.10ab','Omsluttende 6.10a og 6.10b'],['6.10','6.10']]);
 for(const [id,label,value]of [['gammaG','γG',1.35],['gammaQ','γQ',1.5],['xi','ξ',.85],['gammaM','γM heltre',1.3],['glulamGammaM','γM limtre',1.25],['kcr','kcr skjær',.67]])field(basis,'terrace-'+id,label,value);
 for(const [name,values]of [['live',[.7,.5,.3]],['snow',[.5,.2,0]]])for(let i=0;i<3;i++)field(basis,name+'Psi'+i,(name==='live'?'Nyttelast':'Snølast')+' ψ'+i,values[i]);
 field(basis,'terraceStandardSource','Standardutgave og NA-kilde','').inputMode='text';controls.terraceStandardSource.required=false;
 tick(basis,'terraceRestrained','Trykksidens fastholding og sideveis avstivning er dokumentert');tick(basis,'terraceSupportsVerified','Opplegg og lastvei er dokumentert');tick(basis,'terraceConfirmed','Prosjektets standardutgaver og NA-faktorer er kontrollert');
 const sources=el('p',undefined,'muted');for(const [title,url]of [['Standard Norge',terraceSources.national],['EN-laster',terraceSources.loads],['Trematerialer / EC5',terraceSources.timber]]){const a=el('a',title);a.href=url;a.target='_blank';a.rel='noopener';sources.append(a,document.createTextNode(' · '));}basis.parentElement.append(sources);
 const submit=el('button','Beregn spenn og lag 2D-plan','terrace-submit');submit.type='submit';form.append(error,submit);root.append(form,resultRoot);
 const workspace=el('section',undefined,'terrace-workspace'),drawing=el('div',undefined,'terrace-drawing'),tools=el('div',undefined,'terrace-toolbar'),drawingNote=el('p',undefined,'muted');workspace.hidden=true;workspace.append(el('h3','2D-plan: bjelker, dragere og stolper'),el('p','Velg og flytt en dragerlinje eller stolperekke. Kantene er faste. Du kan også skrive inn koordinaten. Endret geometri må beregnes på nytt.','muted'),tools,drawing,drawingNote);root.append(workspace);
 const selectedLabel=el('span','Ingen linje valgt'),lineChoice=el('select'),coordinate=el('input');lineChoice.setAttribute('aria-label','Velg linje i 2D-planen');lineChoice.onchange=()=>{if(lineChoice.value){const [type,index]=lineChoice.value.split(':');choose(type,Number(index));}};coordinate.type='number';coordinate.step='.1';coordinate.min='.1';coordinate.setAttribute('aria-label','Koordinat for valgt linje (m)');coordinate.disabled=true;
 const move=el('button','Flytt valgt linje','secondary');move.type='button';move.disabled=true;tools.append(selectedLabel,lineChoice,coordinate,move);
 function button(label,fn){const b=el('button',label,'secondary');b.type='button';b.onclick=fn;tools.append(b);return b;}
 function invalidate({geometryChanged=false}={}){result=null;resultRoot.replaceChildren();resultRoot.hidden=true;error.textContent='';drawingNote.textContent=workspace.hidden?'':'Planen er endret. Beregn på nytt for å oppdatere lastene og kapasiteten.';save.disabled=true;if(geometryChanged){rowYs=null;supportXs=null;selected=null;coordinate.disabled=move.disabled=true;workspace.hidden=true;}else if(rowYs&&supportXs)sketch();}
 function number(id){const s=controls[id].value.trim();if(!/^\d+(?:[.,]\d+)?$/.test(s))throw Error('Oppgi tall i «'+controls[id].parentElement.querySelector('span').textContent+'».');return Number(s.replace(',','.'));}
 function input(){const p={};for(const key of ['deckThicknessMm','deckWidthMm','deckGapMm','deckDensityKgM3','additionalDeadKnM2','liveKnM2','pointKn','spacingMm','beamCount','joistWidthMm','joistHeightMm','beamWidthMm','beamHeightMm'])p[key]=number(key);
  Object.assign(p,{lengthM:number('terraceLengthM'),depthM:number('terraceDepthM'),heightM:number('terraceHeightM'),wallSupport:controls.wallSupport.value,joistGrade:controls.joistGrade.value,beamGrade:controls.beamGrade.value,equalSharing:controls.equalSharing.checked,loadSource:controls.loadSource.value.trim(),snowStatus:controls.snowStatus.value,snowKnM2:controls.snowStatus.value==='documented'?number('snowKnM2'):0,snowSource:controls.snowSource.value.trim(),serviceClass:number('terraceServiceClass'),limitRatio:number('terraceLimitRatio'),bearingMm:number('terraceBearingMm'),restrained:controls.terraceRestrained.checked,supportsVerified:controls.terraceSupportsVerified.checked,glulamGammaM:number('terrace-glulamGammaM')});
  p.livePsi={};p.snowPsi={};for(let i=0;i<3;i++){p.livePsi['psi'+i]=number('livePsi'+i);p.snowPsi['psi'+i]=number('snowPsi'+i);}
  p.profile={...terraceEnProfile,expression:controls.terraceExpression.value,source:controls.terraceStandardSource.value.trim(),confirmed:controls.terraceConfirmed.checked};for(const key of ['gammaG','gammaQ','xi','gammaM','kcr'])p.profile[key]=number('terrace-'+key);if(rowYs)p.rowYs=rowYs;if(supportXs)p.supportXs=supportXs;return p;
 }
 function list(target,title,items){if(!items.length)return;target.append(el('h3',title));const ul=el('ul');items.forEach(t=>ul.append(el('li',t)));target.append(ul);}
 function renderReport(r){resultRoot.replaceChildren();resultRoot.hidden=false;
  resultRoot.append(el('p',r.status==='within_member_scope'?'Innenfor beregnet medlemsomfang':r.status==='exceeded'?'Overskredet – endre plan eller dimensjoner':'Foreløpig beregning – se avklaringer','eyebrow'),el('h2','Spennet er beregnet fra dimensjoner og laster'));
  const metrics=el('dl',undefined,'result-metrics');for(const [label,value]of [['Største beregnede bjelkespenn',fmt(r.joistLimit.limitM,3)+' m'],['Største dragerspenn i denne planen',r.largestBeamSpanM===null?'Ikke bestått':fmt(r.largestBeamSpanM,3)+' m'],['Støttepunkter',r.supportCount],['Egenlast bord og ekstra lag',fmt(r.loadBasis.deckKnM2,3)+' kN/m²']]){const box=el('div');box.append(el('dt',label),el('dd',String(value)));metrics.append(box);}resultRoot.append(metrics,el('p','Styrende for største bjelkespenn: '+r.joistLimit.calculation.governing.name+'. Planen har '+r.beamRowCount+' dragerlinjer og '+r.joistCount+' tverrbjelker med faktisk c/c '+fmt(r.loadBasis.actualSpacingM*1000,0)+' mm.'));
  resultRoot.append(el('p','Største dragerspenn gjelder den lengste beståtte planen med like stolpeavstander. Etter flytting kontrolleres hvert felt med bjelkenes faktiske punktreaksjoner. Det er ikke en generell spennvidde for andre lastbredder.','muted'));
  list(resultRoot,'Dette må avklares',r.notPerformed);list(resultRoot,'Stolper, forbindelser og fundament',r.required);
  const details=el('details');details.append(el('summary','Laster, medlemskontroller og oppleggsreaksjoner'));
  details.append(el('p','Bordegenlast: tykkelse × dekningsgrad × densitet × 9,81. Bjelkene veier '+fmt(r.loadBasis.joistWeightKnM,3)+' kN/m og hver dragerplanke '+fmt(r.loadBasis.beamWeightKnM,3)+' kN/m. Nyttelast: '+fmt(r.input.liveKnM2)+' kN/m²; alternativ punktlast '+fmt(r.input.pointKn)+' kN.'));
  const table=el('table'),head=el('tr');['Medlem / plassering','Spenn','Styrende kontroll','Utnyttelse'].forEach(t=>head.append(el('th',t)));table.append(head);
 for(const c of r.checks){const tr=el('tr');[c.role==='joist'?'Bjelke y '+fmt(c.y0M)+'–'+fmt(c.y1M):c.role==='contact'?'Opplegg x '+fmt(c.xM)+', y '+fmt(c.yM):'Drager y '+fmt(c.yM)+', x '+fmt(c.x0M)+'–'+fmt(c.x1M),c.role==='contact'?'—':fmt(c.spanM)+' m',c.result.governing.name,fmt(c.result.governing.utilization*100)+' %'].forEach(t=>tr.append(el('td',t)));table.append(tr);}const scroll=el('div',undefined,'basis-scroll');scroll.append(table);details.append(scroll);
  const rt=el('table'),rh=el('tr');['Stolpe x/y (m)','Gk (kN)','Qk (kN)','Snø (kN)'].forEach(t=>rh.append(el('th',t)));rt.append(rh);for(const s of r.supports){const tr=el('tr');[fmt(s.xM)+' / '+fmt(s.yM),fmt(s.gkKn),fmt(s.qkKn),r.input.snowStatus==='documented'?fmt(s.snowKn):'Uavklart / ikke aktuell'].forEach(t=>tr.append(el('td',t)));rt.append(tr);}const rs=el('div',undefined,'basis-scroll');rs.append(rt);details.append(rs);
  details.append(el('p','Lastlikevekt Gk: '+fmt(r.equilibrium.gReactionKn,3)+' / '+fmt(r.equilibrium.gExpectedKn,3)+' kN. Qk: '+fmt(r.equilibrium.qReactionKn,3)+' / '+fmt(r.equilibrium.qExpectedKn,3)+' kN. Reaksjoner ved huset er med i likevekten.'));
  const data=el('details');data.append(el('summary','Standardfaktorer og beregningsgrunnlag'),el('pre',JSON.stringify(r.input,null,2)));details.append(data);list(details,'Modellforutsetninger',r.assumptions);resultRoot.append(details);
 }
 function clearSelection(){selected=null;selectedLabel.textContent='Ingen linje valgt';coordinate.disabled=move.disabled=true;lineChoice.value='';}
 function choose(type,index){selected={type,index};lineChoice.value=type+':'+index;const values=type==='row'?rowYs:supportXs;selectedLabel.textContent=(type==='row'?'Dragerlinje y':'Stolperekke x')+' = '+fmt(values[index])+' m';coordinate.value=values[index].toFixed(2);coordinate.max=(type==='row'?number('terraceDepthM'):number('terraceLengthM'))-.1;coordinate.disabled=move.disabled=index===0||index===values.length-1;}
 function sketch(){if(!rowYs||!supportXs)return;workspace.hidden=false;const plan={kind:'terrace_sketch',input:{lengthM:number('terraceLengthM'),depthM:number('terraceDepthM')},rows:rowYs.map((yM,i)=>({yM,type:i===0&&controls.wallSupport.value==='documented'?'wall':'beam'})),supports:rowYs.flatMap((yM,i)=>i===0&&controls.wallSupport.value==='documented'?[]:supportXs.map(xM=>({xM,yM}))),joistCount:Math.ceil(number('terraceLengthM')/(number('spacingMm')/1000))+1};renderTerracePlan(drawing,result||plan);
  const empty=el('option','Velg dragerlinje / stolperekke');empty.value='';lineChoice.replaceChildren(empty);for(const [type,values]of [['row',rowYs],['column',supportXs]])values.forEach((v,i)=>{const o=el('option',(type==='row'?'Dragerlinje y ':'Stolperekke x ')+fmt(v)+' m'+(i===0||i===values.length-1?' · fast kant':''));o.value=type+':'+i;lineChoice.append(o);});if(selected)lineChoice.value=selected.type+':'+selected.index;
  const svg=drawing.querySelector('svg'),L=plan.input.lengthM,D=plan.input.depthM,scale=Math.min(620/L,290/D),NS='http://www.w3.org/2000/svg';
  for(const [type,values]of [['row',rowYs],['column',supportXs]])values.forEach((v,i)=>{const handle=document.createElementNS(NS,'circle');handle.setAttribute('cx',type==='row'?90+L*scale+14:90+v*scale);handle.setAttribute('cy',type==='row'?80+v*scale:64);handle.setAttribute('r',9);handle.setAttribute('class','terrace-handle');handle.setAttribute('role','button');handle.setAttribute('tabindex','0');handle.setAttribute('aria-label',(type==='row'?'Velg dragerlinje':'Velg stolperekke')+' '+fmt(v)+' m');handle.addEventListener('click',()=>choose(type,i));handle.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();choose(type,i);}});
   handle.addEventListener('pointerdown',event=>{if(i===0||i===values.length-1)return;event.preventDefault();choose(type,i);handle.setPointerCapture(event.pointerId);const matrix=svg.getScreenCTM().inverse();function moved(e){const point=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix),position=((type==='row'?point.y-80:point.x-90)/scale);coordinate.value=(Math.round(Math.max(values[i-1]+.1,Math.min(values[i+1]-.1,position))*10)/10).toFixed(1);}function ended(e){moved(e);handle.removeEventListener('pointermove',moved);handle.removeEventListener('pointerup',ended);move.click();}handle.addEventListener('pointermove',moved);handle.addEventListener('pointerup',ended);});svg.append(handle);});
 }
 move.onclick=()=>{try{const axis=selected.type==='row'?rowYs:supportXs,index=selected.index,n=Number(coordinate.value);if(!Number.isFinite(n)||n<axis[index-1]+.1-eps||n>axis[index+1]-.1+eps)throw Error('Plasser linjen mellom naboene med minst 0,1 m avstand.');axis[index]=n;controls.terraceConfirmed.checked=false;invalidate();sketch();choose(selected.type,index);}catch(e){error.textContent=e.message;}};
 function addLine(type){const axis=type==='row'?rowYs:supportXs;if(!axis)return;let index=0;for(let i=1;i<axis.length-1;i++)if(axis[i+1]-axis[i]>axis[index+1]-axis[index])index=i;if(axis[index+1]-axis[index]<.2)return;axis.splice(index+1,(0),(axis[index+1]+axis[index])/2);controls.terraceConfirmed.checked=false;invalidate();sketch();choose(type,index+1);}
 button('+ Dragerlinje',()=>addLine('row'));button('+ Stolperekke',()=>addLine('column'));
 button('Fjern valgt linje',()=>{if(!selected)return;const axis=selected.type==='row'?rowYs:supportXs;if(selected.index===0||selected.index===axis.length-1)return;axis.splice(selected.index,1);controls.terraceConfirmed.checked=false;selected=null;coordinate.disabled=move.disabled=true;selectedLabel.textContent='Ingen linje valgt';invalidate();sketch();});
 button('Fordel automatisk igjen',()=>{rowYs=supportXs=null;clearSelection();controls.terraceConfirmed.checked=false;invalidate();form.requestSubmit();});
 function download(data,type,filename){const url=URL.createObjectURL(new Blob([data],{type})),a=el('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 button('Last ned 2D-skisse (SVG)',()=>{const svg=drawing.querySelector('svg').cloneNode(true);svg.querySelectorAll('.terrace-handle').forEach(h=>h.remove());svg.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='text{font-family:Arial,sans-serif}';svg.prepend(style);download(new XMLSerializer().serializeToString(svg),'image/svg+xml','rigor-terrasse-2d.svg');});
 const save=button('Last ned beregning (JSON)',()=>{if(result)download(JSON.stringify(result,null,2),'application/json','rigor-terrasse-beregning.json');});
 function sync(){for(const role of ['joist','beam']){const custom=controls[role+'Section'].value==='custom';for(const k of ['WidthMm','HeightMm']){controls[role+k].parentElement.hidden=!custom;controls[role+k].required=custom;}}
  const known=controls.snowStatus.value==='documented';controls.snowKnM2.parentElement.hidden=!known;controls.snowKnM2.required=known;controls.snowSource.required=controls.snowStatus.value!=='unknown';controls.snowSource.parentElement.hidden=controls.snowStatus.value==='unknown';save.disabled=!result;
 }
 for(const role of ['joist','beam'])controls[role+'Section'].addEventListener('change',()=>{if(controls[role+'Section'].value!=='custom'){const [w,h]=controls[role+'Section'].value.split('x');controls[role+'WidthMm'].value=w;controls[role+'HeightMm'].value=h;}sync();});
 controls.useCase.addEventListener('change',()=>{if(controls.useCase.value==='residential'){controls.liveKnM2.value='4';controls.pointKn.value='3';controls.loadSource.value=source;}});
 form.addEventListener('input',event=>{if(event.target!==controls.terraceConfirmed)controls.terraceConfirmed.checked=false;invalidate({geometryChanged:['terraceLengthM','terraceDepthM','spacingMm'].includes(event.target.name)});sync();});form.addEventListener('change',event=>{if(event.target!==controls.terraceConfirmed)controls.terraceConfirmed.checked=false;invalidate({geometryChanged:['terraceLengthM','terraceDepthM','spacingMm'].includes(event.target.name)});sync();});
 form.onsubmit=event=>{event.preventDefault();error.textContent='';try{result=designTerrace(input());rowYs=result.rowYs;supportXs=result.supportXs;renderReport(result);sketch();if(selected)choose(selected.type,selected.index);drawingNote.textContent=result.passed?'Planens bjelke- og dragerfelt er innenfor beregnede kontroller. Se avklaringer før planen brukes.':'Ett eller flere felt er overskredet. Flytt eller legg til støtte, eller øk dimensjonen.';sync();}catch(e){result=null;resultRoot.hidden=true;error.textContent=e.message;sync();}};
 sync();resultRoot.hidden=true;
 return {open(context){if(context){for(const id of ['terraceLengthM','terraceDepthM','terraceHeightM','spacingMm'])if(context.facts?.[id])controls[id].value=String(context.facts[id].value);if(context.facts?.terraceWallSupport)controls.wallSupport.value=context.facts.terraceWallSupport.value;}invalidate({geometryChanged:true});sync();}};
}
const eps=1e-8;
