// RIGOR's own editable templates. Times/consumption are assumptions, not industry norms.
// task(id, title, hours/unit, price key, demonstration price, material unit, consumption)
const task=(id,name,hours,priceKey=null,exampleMaterial=0,materialUnit='m²',materialRatio=1)=>({id,name,hours,priceKey,exampleMaterial,materialUnit,materialRatio});
export const roofTypes={
 flat:{name:'Flatt tak',note:'Lavt fall. Kontroller falloppbygging, sluk, overløp og oppkanter. Membran er foreslått tekking.'},
 shed:{name:'Pulttak',note:'Én skrå takflate. Kontroller høy og lav avslutning samt beslag.'},
 gable:{name:'Saltak',note:'To takflater. Horisontalt areal kan omregnes når begge sider har lik takvinkel.'},
 hip:{name:'Valmtak',note:'Flere takflater. Arealomregning forutsetter lik takvinkel på alle flater. Oppgi valmlengdene separat.'},
 mansard:{name:'Mansardtak',note:'To vinkler og knekk i takflatene. Ved projisert areal må andelen øvre tak og begge vinkler oppgis. Kontroller knekkbeslag separat.'}
};
export const library=[
 {id:'roof.removal',name:'Rive eksisterende taktekking',category:'40 · Tak / Riving',trade:'Tømrer',type:'Rehab',unit:'m²',tasks:[task('cover','Rive tekking',.15),task('clean','Renske underlag og festemidler',.10)]},
 {id:'roof.underlay',name:'Undertak, sløyfer og lekter',category:'41 · Tak / Underlag',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('underlay','Legge undertak',.25,'roof.underlay.undertak',140),task('battens','Montere sløyfer',.12,'roof.underlay.sloyfer',24,'m',1.67),task('laths','Montere lekter',.13,'roof.underlay.lekter',30,'m',2)]},
 {id:'roof.deck',name:'Fast underlag for membran',category:'41 · Tak / Underlag',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('deck','Montere taktro / plateunderlag',.30,'roof.deck',180)]},
 {id:'roof.cover.metal',name:'Metalltekking',category:'42 · Tak / Tekking',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('cover','Montere metalltekking',.35,'roof.cover.metal',290)]},
 {id:'roof.cover.tile',name:'Takstein',category:'42 · Tak / Tekking',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('cover','Legge takstein',.35,'roof.cover.tile',350)]},
 {id:'roof.cover.membrane',name:'Takmembran',category:'42 · Tak / Tekking',trade:'Taktekker',type:'Alle',unit:'m²',tasks:[task('cover','Legge / sveise takmembran',.40,'roof.cover.membrane',230)]},
 {id:'roof.ridge',name:'Møne',category:'43 · Tak / Beslag og avslutninger',trade:'Taktekker',type:'Alle',unit:'m',measure:'ridgeLength',tasks:[task('ridge','Montere mønebeslag / mønestein',.15,'roof.ridge',120,'m')]},
 {id:'roof.hip',name:'Valmer',category:'43 · Tak / Beslag og avslutninger',trade:'Taktekker',type:'Alle',unit:'m',measure:'hipLength',tasks:[task('hip','Montere valmbeslag / valmstein',.20,'roof.hip',140,'m')]},
 {id:'roof.break',name:'Knekk i mansardtak',category:'43 · Tak / Beslag og avslutninger',trade:'Taktekker',type:'Alle',unit:'m',measure:'breakLength',tasks:[task('break','Montere knekkbeslag',.25,'roof.break',170,'m')]},
 {id:'roof.edge',name:'Kantbeslag og takfot',category:'43 · Tak / Beslag og avslutninger',trade:'Taktekker',type:'Alle',unit:'m',measure:'edgeLength',tasks:[task('edge','Montere kant- og takfotbeslag',.18,'roof.edge',110,'m')]},
 {id:'roof.drain',name:'Sluk og overløp',category:'43 · Tak / Beslag og avslutninger',trade:'Taktekker',type:'Alle',unit:'stk',measure:'drainCount',tasks:[task('drain','Montere sluk / overløp',1,'roof.drain',700,'stk')]},
 {id:'roof.rig',name:'Stillas og fallsikring',category:'10 · Rigg, drift og sikring',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('safety','Etablere fallsikring',.04,'roof.rig.sikring',20),task('scaffold','Stillas: montering, demontering og leieavsetning',.08,'roof.rig.stillas',70)]},
 {id:'roof.waste',name:'Transport og avfall',category:'11 · Avfall og transport',trade:'Tømrer',type:'Rehab',unit:'m²',tasks:[task('waste','Håndtere og transportere avfall',.05,'roof.waste',65)]},
 {id:'insulation.removal',name:'Rive ytterkledning',category:'30 · Yttervegg / Riving',trade:'Tømrer',type:'Rehab',unit:'m²',tasks:[task('remove','Rive kledning',.20),task('clean','Renske og klargjøre vegg',.10)]},
 {id:'insulation.insulation',name:'Etterisolering utvendig, 100 mm',category:'31 · Yttervegg / Isolasjon',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('frame','Montere utlekting (forbruk må kontrolleres)',.30,'insulation.utlekting',45,'m',1.67),task('insulation','Montere 100 mm isolasjon',.25,'insulation.isolasjon100',180)]},
 {id:'insulation.cladding',name:'Vindsperre og ytterkledning',category:'32 · Yttervegg / Kledning',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('barrier','Montere vindsperre',.15,'insulation.vindsperre',60),task('cladding','Montere kledning',.50,'insulation.kledning',320)]},
 {id:'insulation.rig',name:'Stillas ved yttervegg',category:'10 · Rigg, drift og sikring',trade:'Tømrer',type:'Alle',unit:'m²',tasks:[task('rig','Montering, demontering og leieavsetning',.12,'insulation.rig',75)]},
 {id:'insulation.waste',name:'Avfall fra veggarbeid',category:'11 · Avfall og transport',trade:'Tømrer',type:'Rehab',unit:'m²',tasks:[task('waste','Transport og avfall',.05,'insulation.waste',55)]},
 {id:'extension.foundation',name:'Fundament og grunnarbeid (budsjett)',category:'20 · Grunn og fundament',trade:'Betong',type:'Nybygg',unit:'m²',tasks:[task('foundation','Fundament og grunnarbeid – må prosjekteres',1.8,'extension.foundation',2200)]},
 {id:'extension.frame',name:'Bærende konstruksjon og vegger (budsjett)',category:'30 · Yttervegg / Konstruksjon',trade:'Tømrer',type:'Nybygg',unit:'m²',tasks:[task('frame','Konstruksjon per m² gulvareal',4,'extension.frame',4200)]},
 {id:'extension.roof',name:'Tak på tilbygg (budsjett)',category:'42 · Tak / Tekking',trade:'Tømrer',type:'Nybygg',unit:'m²',tasks:[task('roof','Takavsetning per m² gulvareal',1.5,'extension.roof',1600)]},
 {id:'extension.interior',name:'Innvendige overflater (budsjett)',category:'50 · Innvendig / Overflater',trade:'Tømrer',type:'Nybygg',unit:'m²',tasks:[task('interior','Innvendige overflater per m² gulvareal',2.5,'extension.interior',1800)]},
 {id:'extension.technical',name:'Elektro og VVS (budsjett)',category:'60 · Tekniske fag',trade:'Tekniske fag',type:'Nybygg',unit:'m²',tasks:[task('technical','Avsetning – innhent fagtilbud',0,'extension.technical',2200)]},
 {id:'extension.rig',name:'Rigg på tilbygg',category:'10 · Rigg, drift og sikring',trade:'Tømrer',type:'Nybygg',unit:'m²',tasks:[task('rig','Rigg og drift per m² gulvareal',.7,'extension.rig',650)]}
];

// Scope descriptions distinguish work packages from products and budget allowances.
const scope = {
 'roof.removal':['Demontering av eksisterende tekking og rensk av underlaget før videre takarbeid.','Målt takflate som faktisk skal rives.','Riving av undertak, sløyfer og lekter; stillas; transport og avfallsavgifter.'],
 'roof.underlay':['Nytt undertak med sløyfer og lekter på eksisterende bærende konstruksjon.','Målt takflate. Sløyfe- og lekteforbruk må tilpasses sperreavstand og valgt tekking.','Taktro, utskifting av sperrer, isolasjon, tekking og beslag.'],
 'roof.deck':['Fast taktro eller plateunderlag som skal bære takmembranen.','Målt takflate. Velg platetype, tykkelse og innfesting etter konstruksjonen.','Bærende konstruksjon, falloppbygging, isolasjon og membran.'],
 'roof.cover.metal':['Montering av metalltekking på ferdig, egnet underlag.','Målt takflate. Avklar profil, materiale, overlapp og festemidler.','Undertak, lekter, møne, valmer, gjennomføringer og kantbeslag.'],
 'roof.cover.tile':['Legging av takstein på ferdig lektet tak.','Målt takflate. Avklar betong-/teglstein, lekteavstand og vekt.','Undertak, lekting, mønestein, valmstein, snøfangere og stillas.'],
 'roof.cover.membrane':['Legging eller sveising av membran på egnet underlag.','Målt takflate. Avklar system, lagantall og produktets krav til fall.','Isolasjon, falloppbygging, oppkanter, sluk og gjennomføringer.'],
 'roof.ridge':['Avslutning langs horisontalt møne med egnet beslag eller mønestein.','Samlet faktisk mønelengde i meter.','Valmer, mansardknekk, ventilasjonsløsning og taktekking.'],
 'roof.hip':['Avslutning langs skrå valmer på valmtak.','Summen av alle valmenes faktiske lengder i meter.','Horisontalt møne, tekking og ekstra kapp/svinn utenfor denne posten.'],
 'roof.break':['Beslag i overgangen mellom øvre og nedre takflate på mansardtak.','Samlet lengde langs alle knekkene i meter.','Møne, takfot, endebeslag og tekking av selve flatene.'],
 'roof.edge':['Kant- og takfotbeslag langs avtalte takavslutninger.','Samlet lengde i meter. Unngå å telle samme kant to ganger.','Takrenner, nedløp, møne, valmer og pipebeslag.'],
 'roof.drain':['Montering av taksluk eller overløp som egen stykkpost.','Antall sluk/overløp. Avklar type og dimensjon per post.','Rørføring, tilkobling, frostsikring og falloppbygging.'],
 'roof.rig':['Foreløpig samlet avsetning til stillas og fallsikring ved takarbeid.','Takareal brukes kun som budsjettgrunnlag; innhent faktisk rigg- og leietilbud.','Separat kran, lift, lang leieperiode og offentlig arealbruk.'],
 'roof.waste':['Foreløpig avsetning til håndtering og transport av takavfall.','Areal som rives. Avklar avfallsfraksjoner, vekt, container og transport.','Farlig avfall og særskilte mottaks-/saneringskostnader.'],
 'insulation.removal':['Riving av ytterkledning og klargjøring av eksisterende vegg.','Netto veggflate som rives, etter fradrag for avtalte åpninger.','Sanering, reparasjon av råte, ny isolasjon og borttransport.'],
 'insulation.insulation':['Utvendig utlekting og 100 mm etterisolering av eksisterende vegg.','Netto veggflate. Trelastforbruk og c/c-avstand må kontrolleres.','Vindsperre, kledning, vindustilpasning og fuktteknisk prosjektering.'],
 'insulation.cladding':['Vindsperre og ytterkledning uten utskifting av bærende vegg.','Netto veggflate; avklar profil, lufting, hjørner og svinn.','Etterisolering, vinduer, beslag, overflatebehandling og stillas.'],
 'insulation.rig':['Foreløpig stillasavsetning ved fasadearbeid.','Veggareal er budsjettgrunnlag; faktisk stillashøyde og leietid må avklares.','Lift, kran, tillatelser og tildekking utover avtalt omfang.'],
 'insulation.waste':['Foreløpig avfallsavsetning ved riving av yttervegg.','Areal som rives, med dokumentert transport- og mottaksgrunnlag.','Farlig avfall og sanering.'],
 'extension.foundation':['Grovt budsjett for grunnarbeid og fundamentering til et tilbygg.','Gulvareal som budsjettgrunnlag; erstattes med prosjekterte mengder.','Geoteknikk, sprenging, masseutskifting og dokumentert fundamentdimensjonering.'],
 'extension.frame':['Grovt budsjett for bærende konstruksjon og yttervegger.','Gulvareal; ikke faktisk veggflate eller dimensjonert konstruksjon.','Prosjektering, spesielle laster og detaljerte produkt-/veggoppskrifter.'],
 'extension.roof':['Grovt takbudsjett per m² gulvareal til tilbygg.','Gulvareal; erstattes med faktisk takflate og egne takoppgaver ved detaljkalkyle.','Geometrisk takberegning og dokumentert innhold i takkonstruksjonen.'],
 'extension.interior':['Grovt budsjett for innvendige overflater i et tilbygg.','Gulvareal som budsjettgrunnlag, ikke mengde for hvert rom og hver overflate.','Våtrom, kjøkken, spesialinnredning og romspesifikke løsninger.'],
 'extension.technical':['Budsjettavsetning til elektro og VVS.','Gulvareal; beløpet må erstattes eller bekreftes med fagtilbud.','Prosjektering og garantier om komplett teknisk leveranse.'],
 'extension.rig':['Foreløpig rigg- og driftsbudsjett for tilbygg.','Gulvareal; avklar byggetid, adkomst og faktisk riggplan.','Spesifikke leieavtaler og særskilte tiltak utenfor riggplanen.']
};
for(const e of library){const [description,quantityNote,excludes]=scope[e.id];Object.assign(e,{description,quantityNote,excludes});}

// Additional selectable scopes have no invented prices or time norms.
// The user must supply time/unit and import/register prices before a total is shown.
function addElement(id,name,category,trade,type,unit,description,quantityNote,excludes,steps){
 library.push({id,name,category,trade,type,unit,description,quantityNote,excludes,tasks:steps.map(([key,title,materialUnit=unit,ratio=1])=>({...task(key,title,0,materialUnit===null?null:id+'.'+key,0,materialUnit||unit,ratio),requiresTime:!['rent','disposal'].includes(key)}))});
}
function labor(key,title){return [key,title,null];}
for(const [id,label] of [['tile','takstein'],['metal','metallplater'],['membrane','takmembran / asfaltbelegg']]){
 addElement('roof.remove.'+id,'Riving av '+label,'40 · Tak / Riving','Tømrer','Rehab','m²','Selektiv demontering av '+label+' og klargjøring for nytt tak.','Faktisk takflate som skal rives. Avklar om materialet skal sorteres eller gjenbrukes.','Undertak, lekter, stillas og avfallsmottak prises i egne elementer.',[labor('detach','Løsne og demontere '+label),labor('sort','Sortere og samle revet tekking'),labor('clean','Renske festemidler og kontrollere underlag')]);
}
addElement('roof.remove.structure','Rive sløyfer, lekter og undertak','40 · Tak / Riving','Tømrer','Rehab','m²','Demontering av taklag under eksisterende tekking.','Areal der underlaget skal skiftes. Kryss bort lag som beholdes.','Tekking, bærende sperrer, råtesanering og avfallsmottak.',[labor('laths','Demontere lekter'),labor('battens','Demontere sløyfer'),labor('underlay','Fjerne undertak / underlagsbelegg')]);
for(const [id,label] of [['board','Taktro av bord'],['plywood','Taktro av kryssfiner'],['osb','Taktro av OSB / egnet takplate']]){
 addElement('roof.deck.'+id,label,'41 · Tak / Underlag','Tømrer','Alle','m²',label+' som fast underlag på kontrollert bæring.','Netto takflate. Velg tykkelse, spenn, skjøtestøtte og godkjent produkt før prising.','Bærende konstruksjon, fall, tekking og råteskader.',[['fit','Tilpasse og montere taktro'],['fix','Innfesting og understøtting av skjøter']]);
}
for(const [id,label] of [['concrete','Betongtakstein'],['clay','Tegltakstein'],['steel','Profilerte ståltakplater'],['aluminium','Profilerte aluminiumstakplater'],['shingle','Takshingel'],['bitumen','Asfalt takbelegg'],['pvc','PVC takmembran'],['tpo','TPO takmembran']]){
 addElement('roof.finish.'+id,label,'42 · Tak / Tekking','Taktekker','Alle','m²',label+' på ferdig og egnet underlag.','Faktisk takflate. Angi produkt, overlapp, svinn og leverandørens innfestingskrav.','Underlag, isolasjon, stillas, sluk, møne, valmer og beslag prises separat.',[['cover','Legge / montere '+label.toLowerCase()],['fasten','Innfesting eller skjøtearbeid til valgt system']]);
}
for(const [id,name,unit,desc,excludes,steps] of [
 ['gutters','Takrenner','m','Takrenner med rennekroker og skjøter.','Nedløp, takfotbeslag og stillas.',[['channel','Montere takrenne'],['hooks','Kroker og skjøter (samlet kostnad per meter)']]],
 ['downpipes','Nedløpsrør','m','Nedløp med klamring langs fasaden.','Overvannsanlegg, tilkobling i bakken og takrenner.',[['pipe','Montere nedløpsrør'],['brackets','Klamring og bend (samlet kostnad per meter)']]],
 ['chimney','Pipebeslag','stk','Tetning og beslag rundt eksisterende pipe.','Piperehabilitering, murarbeid og brannprosjektering.',[['flashing','Tilpasse og montere pipebeslag'],['sealing','Tette overgang mot tekking']]],
 ['roofwindow','Takvindu','stk','Innsetting av takvindu i avklart takåpning.','Bærende ombygging, elektrisk tilkobling og innvendige utforinger.',[['window','Montere vindu'],['flashing','Inndekning og tetting mot tak']]],
 ['snowguard','Snøfanger','m','Snøfanger med systemtilpassede innfestinger.','Dimensjonering etter snølast og oppgradering av bærende konstruksjon.',[['guard','Montere snøfanger'],['anchors','Innfestingskomponenter per meter']]],
 ['ladder','Takstige / gangbane','m','Fast adkomstløsning på taket.','Dimensjonering og kravavklaring med feier.',[['access','Montere takstige eller gangbane'],['anchors','Systemtilpasset innfesting per meter']]],
 ['upstand','Membran på oppkant','m','Oppbrett og avslutning langs oppkant på flatt tak.','Selve oppkantkonstruksjonen og flate membranarbeider.',[['membrane','Montere oppbrett av membran'],['finish','Avslutningsprofil og tetting']]],
 ['valley','Kilrenne / gradrenne','m','Beslag og tetting i innvendige takrenner mellom takflater.','Ombygging av bæring og flate takarbeider.',[['valley','Montere kilrennebeslag'],['seal','Tetning og tilpasning av tekking']]]
 ])addElement('roof.detail.'+id,name,'43 · Tak / Beslag og avslutninger','Taktekker','Alle',unit,desc,unit==='stk'?'Antall enheter. Avklar størrelse og produkt separat.':'Faktisk montert lengde i meter; ikke takareal.',excludes,steps);
for(const thickness of [100,150,200,250])addElement('roof.insulation.'+thickness,'Takisolasjon '+thickness+' mm','44 · Tak / Isolasjon','Tømrer','Alle','m²','Isolasjonslag med nominell tykkelse '+thickness+' mm.','Areal som isoleres. Avklar produkttype, varmeledningsevne, tettesjikt og konstruksjon.','Dampsperre, vindsperre, lufting og fuktteknisk prosjektering.',[['insulate','Tilpasse og legge '+thickness+' mm isolasjon']]);
for(const thickness of [50,150,200])addElement('wall.insulation.'+thickness,'Utvendig etterisolering '+thickness+' mm','31 · Yttervegg / Isolasjon','Tømrer','Rehab','m²','Utvendig etterisolering med separat utlekting og isolasjonslag.','Netto veggflate. Trelastforbruk må oppgis fra valgt c/c og faktisk veggoppbygging.','Kledning, vindustilpasning, beslag og fuktprosjektering.',[['frame','Utlekting (samlet materialkostnad per m² vegg)'],['insulate',thickness+' mm isolasjon']]);
for(const [id,label] of [['horizontal','liggende trekledning'],['vertical','stående trekledning']])addElement('wall.cladding.'+id,'Yttervegg med '+label,'32 · Yttervegg / Kledning','Tømrer','Alle','m²','Vindsperre, lufting og '+label+'.','Netto veggflate. Kontroller hjørner, omramming, profil og materialforbruk.','Isolasjon, vinduer, maling og stillas.',[['barrier','Montere vindsperre'],['ventilation','Lufting / lekting (samlet materialkostnad per m²)'],['cladding','Montere '+label]]);
for(const [id,label] of [['window','Vindu'],['exterior-door','Ytterdør']])addElement('openings.replace.'+id,'Skifte '+label.toLowerCase(),'33 · Vinduer og ytterdører','Tømrer','Rehab','stk','Utskifting av '+label.toLowerCase()+' i eksisterende åpning.','Antall enheter med samme størrelse og spesifikasjon; ulike typer legges i separate elementer.','Bærende endringer, stillas, sanering og produktspesifikk prosjektering.',[['remove','Demontere eksisterende '+label.toLowerCase()],['install','Montere ny '+label.toLowerCase()],['seal','Isolere og tette rundt karm (kostnad per åpning)'],['trim','Utforing, lister og beslag (kostnad per åpning)']]);
for(const [id,label] of [['gypsum','gips'],['panel','panel'],['mdf','MDF-plater']])addElement('interior.wall.'+id,'Innvendig vegg med '+label,'50 · Innvendig / Vegger','Tømrer','Alle','m²','Montering av '+label+' på egnet, klargjort underlag.','Netto veggflate. Avklar lagantall, platetykkelse og skjøtebehandling.','Stenderverk, isolasjon, elektriske arbeider og maling.',[['lining','Tilpasse og montere '+label],['joints','Festemidler og skjøtearbeid']]);
for(const [id,label] of [['parquet','parkett'],['laminate','laminat'],['wood','heltregulv']])addElement('interior.floor.'+id,'Legge '+label,'51 · Innvendig / Gulv','Tømrer','Alle','m²','Gulvlegging på avklart og egnet underlag.','Netto gulvareal. Kontroller fukt, planhet, svinn og leverandørens leggekrav.','Riving, avretting, gulvvarme og gulvlister.',[['underlay','Legge gulvunderlag'],['floor','Tilpasse og legge '+label]]);
for(const [id,label] of [['gypsum','gips'],['panel','panel']])addElement('interior.ceiling.'+id,'Himling med '+label,'52 · Innvendig / Himling','Tømrer','Alle','m²','Montering av '+label+' i himling på egnet underlag.','Faktisk himlingsflate. Avklar høyde, lagantall og innfesting.','Bæring, isolasjon, elektriske arbeider og maling.',[['lining','Tilpasse og montere '+label],['joints','Innfesting og skjøtearbeid']]);
addElement('interior.trim','Gulv-, tak- eller karmlister','53 · Innvendig / Listverk','Tømrer','Alle','m','Montering av avtalt listtype med skjøter og hjørner.','Faktisk listelengde i meter. Ulike profiler legges som egne elementer.','Maling, utforinger og reparasjon av underlag.',[['trim','Kappe og montere listverk']]);
addElement('rig.scaffold','Fasadestillas: montering, demontering og leie','10 · Rigg, drift og sikring','Tømrer','Alle','m²','Stillas som egen arbeids- og leiepost.','Stillasflate = lengde × høyde, ikke takflate. Oppgi leiekostnad for hele perioden per m² stillasflate.','Kran, lift, tillatelser og ekstra lang leieperiode utenfor registrert pris.',[['assembly','Montere stillas'],['disassembly','Demontere stillas'],['rent','Stillasleie for avtalt periode']]);
addElement('rig.container','Container og avfallsmottak','11 · Avfall og transport','Tømrer','Rehab','stk','Container med avklart fraksjon, kapasitet og transport.','Antall containere. Prisen må dekke avtalt volum/vekt og antall transporter.','Farlig avfall og overskytende vekt.',[['delivery','Utsetting og henting'],['disposal','Leie og mottaksavgift']]);
addElement('foundation.slab','Plate på mark – detaljert omfang','20 · Grunn og fundament','Betong','Nybygg','m²','Oppgaver for plate på mark etter prosjektert oppbygging.','Plateareal. Omregn prosjektert betongvolum og armering til kostnad per m²; ingen dimensjoner gjettes.','Graving, drenering, sprenging og konstruksjonsprosjektering.',[['base','Avrette og klargjøre bærelag'],['insulation','Legge grunnisolasjon'],['reinforcement','Armering etter tegning'],['concrete','Støping og overflatebearbeiding']]);

export function instantiate(element,quantity,factor=1,selected=element.tasks.map(t=>t.id),instance=''){
 return element.tasks.filter(t=>selected.includes(t.id)).map(t=>({id:element.id+'.'+t.id+instance,elementId:element.id+instance,elementName:element.name,category:element.category,elementDescription:element.description||'',quantityNote:element.quantityNote||'',excludes:element.excludes||'',
 name:t.name,quantity,unit:element.unit,materialQuantity:quantity*t.materialRatio,materialRatio:t.materialRatio,materialUnit:t.materialUnit,material:0,exampleMaterial:t.exampleMaterial,
 hours:t.hours,factor,priceKey:t.priceKey,requiresTime:Boolean(t.requiresTime),needsExamplePrice:Boolean(t.priceKey)&&t.exampleMaterial===0,enabled:true,requiresQuantity:Boolean(element.measure)&&quantity===0}));
}
export function searchLibrary(elements,{search='',trade='Alle',type='Alle',category='Alle'}={}){
 const needle=search.toLocaleLowerCase('nb');
 return elements.filter(e=>(trade==='Alle'||e.trade===trade)&&(type==='Alle'||e.type==='Alle'||e.type===type)&&(category==='Alle'||e.category===category)&&`${e.name} ${e.description||''} ${e.quantityNote||''} ${e.excludes||''} ${e.category} ${e.tasks.map(t=>t.name).join(' ')}`.toLocaleLowerCase('nb').includes(needle));
}
