import {getPortalClient} from './portal-session.js?v=20261007-innlogging';
import {userStorage} from './portal-user-storage.js?v=20261007-brukerlagring';
import {loadPublicCatalog} from './market-public-client.js?v=20261007-avklaringer';
import {selectedPrices,offersForRow,usableOffer} from './market-public-core.js?v=20261007-avklaringer';
import {assistantStatus,requestEstimate} from './ai-estimate-client.js?v=20261007-innlogging';
import {proposalRows,terraceProposalArea,extractMeasurements,validateProposal,clarificationQuestions,appendClarificationAnswers,wizardBrief} from './kalkyle-assistant.js?v=20261007-arbeidstimer';
import {jobs,propose,calculate,roofGeometry,roofConsumption,timeFactor} from './kalkyle-engine.js?v=20261007-arbeidstimer';
import {library,roofTypes,instantiate,searchLibrary} from './kalkyle-library.js?v=20261007-arbeidstimer';
import {parseCsv,validatePrices,applyPrices} from './kalkyle-prices.js?v=20261007-avklaringer';
import {parseTimeCsv,validateTimeCatalog,applyTimeCatalog,restoreAssistantTimes,templateTask} from './kalkyle-time.js?v=20261007-arbeidstimer';
import {fields,prepareImport,sampleImport,checkMapping,mapImport} from './kalkyle-import.js?v=20261005-kategorier';
import {rowCodes,codesFor,exportBasis,csvText} from './kalkyle-codes.js?v=20261007-arbeidstimer';
import {renderCompletion} from './kalkyle-completion.js?v=20261007-arbeidstimer';
import {followupFields} from './kalkyle-questions.js?v=20261007-avklaringer';
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:2}).format(n),num=n=>new Intl.NumberFormat('nb-NO',{maximumFractionDigits:2}).format(n);
const rateKeys=['wage','direct','indirect','billing','laborMarkup','materialMarkup'];
let timeCatalog=[];const rateDefaultKey='rigor-rate-defaults-v1';
let job='roof',rows=[],edited=false,lastSettings=null,result=null;
let priceMode='market',importedPrices=[],marketPrices=[],marketMessage='Leser det offentlige prisregisteret …',priceRequest=0;
let publicCatalog=null,marketBindings={},marketStores={},marketSelectionSignature='';
const roofKeys=['roofType','lowerAngle','upperShare','ridgeLength','hipLength','breakLength','edgeLength','drainCount','battenSpacing','lathSpacing','roofWaste'];
let assistantWizardReview=false;
let renderedGroups=[];let calculationMode='simple';let assistantReady=false,assistantBusy=false,assistantTicket=0,assistantProposal=null,assistantClarifications=[];
function settings(){return {...Object.fromEntries(roofKeys.map(k=>[k,k==='roofType'?$(k).value:Number($(k).value)])),job,area:Number($('area').value),angle:Number($('angle').value),basis:$('basis').value,material:$('material').value,difficulty:Number($('difficulty').value),options:[...document.querySelectorAll('#options input:checked')].map(e=>e.value)};}
function rates(){return Object.fromEntries(rateKeys.map(k=>[k,Number($(k).value)]));}
function valid(){return [...document.querySelectorAll('#questions input[type=number],.rates input')].every(e=>e.disabled||e.checkValidity()) && rows.every(r=>!r.enabled||['quantity','material','hours','factor','materialQuantity'].every(k=>Number.isFinite(r[k])&&r[k]>=0));}
function setupJob(){
 $('jobs').replaceChildren();for(const [key,j] of Object.entries(jobs)){const b=document.createElement('button');b.textContent=j.name;b.setAttribute('aria-pressed',String(key===job));b.onclick=()=>{if(edited&&!confirm('Nye veiviservalg erstatter dine redigerte poster. Fortsette?'))return;job=key;edited=false;setupJob();generate();};$('jobs').append(b);}
 $('options').replaceChildren();for(const [id,title,checked] of [...jobs[job].options,...(job==='roof'?[['details','Ta med møne, beslag og taktypeavhengige detaljer',false]]:[])]){const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.value=id;input.checked=checked;label.append(input,document.createTextNode(title));$('options').append(label);}
 for(const id of ['angle','basis','material','roofType']){$(id).disabled=job!=='roof';$(id+'-label').hidden=job!=='roof';}
 $('area-help').textContent=job==='roof'?'Horisontalt areal omregnes for et enkelt tak med lik vinkel på takflatene. Ta med takutstikk. Bratte tak øker arbeidstiden: +10 % over 25°, +25 % over 40°.':job==='insulation'?'Oppgi netto ytterveggflate som skal etterisoleres.':'Oppgi gulvareal for et tilbygg med én etasje.';
 $('scope-note').textContent='Arbeidstider er eksempler. Rigg og avfall er foreløpig arealbaserte avsetninger; små jobber kan kreve minimumspriser.';
 $('uncertainty').textContent=jobs[job].uncertainty;configureRoof();
}
function configureRoof(){
 $('roof-consumption').hidden=job!=='roof';for(const id of ['battenSpacing','lathSpacing','roofWaste'])$(id).disabled=job!=='roof';
 const roof=job==='roof',type=$('roofType').value,shape=roofTypes[type];
 $('roof-type-note').textContent=roof?shape.note:'';
 $('angle').max=type==='flat'?'5':'75';if(roof&&type==='flat'&&Number($('angle').value)>5)$('angle').value='3';
 for(const o of $('material').options)o.disabled=roof&&type==='flat'&&o.value!=='membrane';if(roof&&type==='flat')$('material').value='membrane';
 $('mansard-fields').hidden=!roof||type!=='mansard';$('lowerAngle').disabled=!roof||type!=='mansard';$('upperShare').disabled=!roof||type!=='mansard'||$('basis').value!=='footprint';
 const details=roof&&Boolean(document.querySelector('#options input[value=details]:checked'));$('roof-details').hidden=!details;
 for(const [id,active] of [['ridgeLength',['gable','hip','mansard'].includes(type)],['hipLength',type==='hip'],['breakLength',type==='mansard'],['edgeLength',true],['drainCount',type==='flat']]){$(id).disabled=!details||!active;$(id+'-label').hidden=!active;}
 if(roof)$('area-help').textContent=type==='mansard'?'Øvre takvinkel oppgis i feltet Takvinkel. Ved projisert areal brukes øvre og nedre vinkel med oppgitt arealandel. Ved målt takflate brukes høyeste vinkel som tidsforutsetning.':'Målt takflate brukes direkte. Projisert areal omregnes med takvinkelen; flatt tak har lavt fall. Arealet inkluderer takutstikk. Tidsfaktorer er foreløpige antakelser.';
}
function generate(){configureRoof();if([...document.querySelectorAll('#questions input[type=number]')].some(e=>!e.disabled&&!e.checkValidity())){update();return;}lastSettings=settings();rows=applyTimeCatalog(propose(lastSettings),timeCatalog);edited=false;renderRows();update();}
function renderRows(){
 $('rows').replaceChildren();renderedGroups=[];
 const groups=new Map();rows.forEach((r,i)=>{const key=r.elementId||r.id||String(i);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(i);});
 for(const indices of groups.values()){
  renderedGroups.push(indices);const first=rows[indices[0]],group=document.createElement('tr');group.className='element-row';group.dataset.elementIndex=indices[0];
  let td=document.createElement('td');td.colSpan=2;td.className='element-title';const title=document.createElement('strong');const elementCode=document.createElement('small');elementCode.className='post-code';elementCode.textContent=rowCodes(first).element;td.append(elementCode);title.textContent=(first.category?first.category+' / ':'')+(first.elementName||first.name);td.append(title);
  const remove=document.createElement('button');remove.type='button';remove.className='element-delete';remove.textContent='Fjern';remove.setAttribute('aria-label','Fjern element '+(first.elementName||first.name));remove.onclick=()=>{rows=rows.filter((r,i)=>!indices.includes(i));edited=true;renderRows();update();};td.append(remove);group.append(td);
  td=document.createElement('td');const qty=document.createElement('input');qty.type='number';qty.min='0';qty.max='1000000';qty.step='any';qty.value=first.quantity;qty.setAttribute('aria-label','Elementmengde '+(first.elementName||first.name));qty.oninput=()=>{const value=qty.value===''?NaN:Number(qty.value);for(const i of indices){const r=rows[i];r.quantity=value;r.materialQuantity=value*(r.materialRatio??1);}edited=true;renderRows();update();document.querySelector(`[data-element-index='${indices[0]}'] input`)?.focus();};td.append(qty);group.append(td);
  td=document.createElement('td');td.textContent=first.unit;group.append(td);td=document.createElement('td');td.colSpan=5;td.append(document.createTextNode(indices.length+' oppgaver · elementmengden oppdaterer alle oppgavene'));const groupHours=document.createElement('small');groupHours.id='group-hours-'+indices[0];td.append(groupHours);group.append(td);
  td=document.createElement('td');td.id='group-total-'+indices[0];group.append(td);$('rows').append(group);
  for(const i of indices){
   const r=rows[i],tr=document.createElement('tr');tr.dataset.rowIndex=i;const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=r.enabled;enabled.setAttribute('aria-label','Inkluder '+r.name);enabled.onchange=()=>{r.enabled=enabled.checked;edited=true;update();};td=document.createElement('td');td.append(enabled);tr.append(td);td=document.createElement('td');td.append(document.createTextNode(r.name));const code=document.createElement('small');code.className='post-code';code.textContent=rowCodes(r).work;const editCode=document.createElement('button');editCode.type='button';editCode.className='code-button';editCode.textContent='Koder';editCode.setAttribute('aria-label','Koder for '+r.name);editCode.onclick=()=>openCodes(r.id);td.append(code,editCode);tr.append(td);
   for(const k of ['quantity','unit','materialQuantity','materialUnit','material','hours','factor']){
    td=document.createElement('td');
    if(k==='unit'||k==='materialUnit')td.textContent=r[k]||r.unit;
    else{
     const input=document.createElement('input');input.type='number';input.min=k==='factor'?'0.01':'0';input.max=k==='factor'?'100':'10000000';input.step='any';input.value=k==='hours'&&r.requiresTime?'':r[k];input.required=!(k==='hours'&&r.requiresTime);if(k==='hours'&&r.requiresTime)input.placeholder='Angi timer';input.dataset.field=k;input.setAttribute('aria-label',r.name+' '+({quantity:'mengde',materialQuantity:'materiellmengde',material:'materialpris',hours:'timer per enhet',factor:'tidsfaktor'}[k]));
     input.oninput=()=>{r[k]=input.value===''?NaN:Number(input.value);if(k==='quantity'){r.materialQuantity=r.quantity*(r.materialRatio??1);tr.querySelector('[data-field=materialQuantity]').value=r.materialQuantity;}if(k==='materialQuantity')r.materialRatio=r.quantity>0?r.materialQuantity/r.quantity:1;if(k==='hours'){r.requiresTime=false;r.manualTime=true;r.timeSource='Registrert i prosjektet';r.timeEstimate=false;r.timeNote='';}if(k==='factor'){r.manualFactor=true;r.timeFactorSource='Registrert i prosjektet';}if(k==='material'){r.manualPrice=true;r.priceIssue=null;}edited=true;update();};td.append(input);
     if(k==='material'){
      const unit=document.createElement('small');unit.className='unit-price-label';unit.textContent='kr/'+(r.materialUnit||r.unit)+' ekskl. MVA';td.append(unit);
      const perWorkUnit=document.createElement('small');perWorkUnit.id='row-material-unit-'+i;perWorkUnit.className='unit-price-label';td.append(perWorkUnit);
      const source=document.createElement('div');source.id='row-source-'+i;source.className='price-meta';td.append(source);
      if(r.priceKey){const choose=document.createElement('button');choose.type='button';choose.id='row-market-'+i;choose.className='secondary row-market-button';choose.textContent='Velg markedsvare';choose.setAttribute('aria-label','Velg markedsvare til '+r.name);choose.onclick=()=>openMaterialDialog(r.id);td.append(choose);}
     }
     if(k==='hours'){const unit=document.createElement('small');unit.textContent='t/'+r.unit;td.append(unit);const info=document.createElement('small');info.id='row-time-'+i;info.className='time-meta';td.append(info);const totalHours=document.createElement('small');totalHours.id='row-work-hours-'+i;totalHours.className='work-hours';td.append(totalHours);const price=document.createElement('small');price.id='row-labor-unit-'+i;price.className='labor-unit-price';td.append(price);}
     if(k==='factor'){const note=document.createElement('small');note.id='row-factor-'+i;note.className='time-meta';td.append(note);}
    }
    tr.append(td);
   }
   td=document.createElement('td');td.id='row-total-'+i;tr.append(td);$('rows').append(tr);
  }
 }
}
function renderRowPrice(row,i){
 const target=$('row-source-'+i),chosen=publicCatalog?.offers.find(o=>o.id===marketBindings[row.priceKey]);target.replaceChildren();
 const issues={mangler:chosen?'Valgt vare har ingen brukbar pris':'Velg vare eller legg inn pris',utdatert:'Prisen er utløpt – hent ny pris',fremtidig:'Prisdato må kontrolleres','feil enhet':'Prisen har en annen materialenhet','pris må registreres':'Legg inn innkjøpspris'};
 if(row.priceIssue)target.textContent=issues[row.priceIssue]||row.priceIssue;
 else if(chosen&&priceMode==='market'&&!row.manualPrice){const link=document.createElement('a');link.href=chosen.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent=chosen.name;target.append(link,document.createTextNode(' · '+chosen.chain+(chosen.store_name?' '+chosen.store_name:'')+' · '+row.priceDate));if(row.marketPackages!==undefined){const note=document.createElement('small');note.textContent='Kjøp '+row.marketPackages+' '+chosen.original_unit+' ('+num(row.marketPurchasedQuantity)+' '+row.materialUnit+')';target.append(note);}}
 else target.textContent=row.priceSource+(row.priceDate?' · '+row.priceDate:'');
 target.classList.toggle('price-warning',Boolean(row.priceIssue));const input=document.querySelector(`[data-row-index='${i}'] [data-field=material]`);if(document.activeElement!==input)input.value=row.priceIssue?'':row.material;input.required=!row.priceIssue;input.disabled=!row.priceKey&&!row.manualPrice;
 $('row-material-unit-'+i).textContent=row.priceKey&&!row.priceIssue&&row.quantity>0&&Number.isFinite((row.marketMaterialCost??row.materialQuantity*row.material)/row.quantity)?'Per '+row.unit+' arbeid: '+money((row.marketMaterialCost??row.materialQuantity*row.material)/row.quantity)+' før påslag':'';
 const choose=$('row-market-'+i);if(choose){choose.hidden=priceMode!=='market';choose.textContent=chosen?'Bytt markedsvare':'Velg markedsvare';}
 $('row-time-'+i).textContent=row.requiresTime?'Grunntid mangler':row.timeSource||'Registrert grunntid';$('row-time-'+i).title=row.timeNote||'';
 $('row-factor-'+i).textContent=row.timeFactorSource||(row.manualFactor?'Egen faktor':row.taskKey?.startsWith('roof.')&&row.unit==='m²'&&lastSettings.job==='roof'?'Takvinkel/adkomst':'Adkomst/utførelse');
}

function update(){
 syncBoundPrices();
 $('task-count').textContent=rows.filter(r=>r.enabled).length+' valgte oppgaver';
 const pricedRows=applyPrices(rows,priceMode,priceMode==='import'?importedPrices:marketPrices);rows.forEach((row,i)=>Object.assign(row,pricedRows[i]));
 const missing=rows.filter(r=>r.enabled&&r.priceIssue),missingTimes=rows.filter(r=>r.enabled&&r.requiresTime),missingQuantities=rows.filter(r=>r.enabled&&r.requiresQuantity&&r.quantity===0);
 const rateValid=rateKeys.every(k=>$(k).checkValidity()),rate=rates(),hourly=rateValid?calculate([],rate,1).hourly:null;
 $('time-overlap').textContent=rows.filter(r=>r.enabled&&r.quantity>0&&r.name==='Demontere terrassebord').length>1?'Demontere terrassebord er valgt i flere elementer. Hvis postene gjelder samme terrasse, fjern én av dem for å unngå dobbel arbeidstid.':'';
 renderCompletion($('simple-completion'),{rows,priceMode,hourly:hourly===null?null:hourly*(1+rate.laborMarkup/100),onMarket:r=>openMaterialDialog(r.id),onPrice:(r,p)=>{if(!p.source){$('status').textContent='Oppgi leverandør eller kilde.';return;}Object.assign(r,{material:p.price,manualPrice:true,manualPriceSource:p.source,manualPriceDate:p.date,priceIssue:null});edited=true;renderRows();update();saveProject();},onQuantity:(r,q)=>{r.quantity=q;r.materialQuantity=q*(r.materialRatio??1);edited=true;renderRows();update();saveProject();},onTime:(r,t)=>{Object.assign(r,{hours:t,requiresTime:false,manualTime:true,timeSource:'Registrert i prosjektet',timeEstimate:false,timeNote:''});edited=true;renderRows();update();saveProject();},onDetails:()=>view(true)});
 $('import-panel').hidden=priceMode!=='import';$('market-panel').hidden=priceMode!=='market';$('price-status').textContent=priceMode==='market'?marketMessage:priceMode==='import'?`Prislisten inneholder ${importedPrices.length} priser. Priser eldre enn 30 dager må oppdateres.`:'Demonstrasjon: prisene er eksempler, ikke markedspriser.';
 renderMarketProducts();$('price-coverage').replaceChildren();rows.forEach(renderRowPrice);
 for(const r of rows.filter(r=>r.enabled)){const li=document.createElement('li');li.textContent=r.name+': '+(r.priceIssue?$('row-source-'+rows.indexOf(r)).textContent:r.priceSource+(r.priceDate?' · '+r.priceDate:''));$('price-coverage').append(li);}
 $('hourly').textContent=rateValid?'Timekostnad: '+money(hourly)+' · Timepris til kunde: '+money(hourly*(1+rate.laborMarkup/100))+' ekskl. MVA':'Fyll inn gyldige timesatser.';
 $('hourly-formula').textContent=rateValid?num(rate.wage)+' × '+num(1+rate.direct/100)+' × '+num(1+rate.indirect/100)+' ÷ '+num(rate.billing/100)+' = '+money(hourly)+' i timekostnad. Kundepris inkluderer '+num(rate.laborMarkup)+' % arbeidspåslag. Alle beregninger bruker uavrundede tall.':'';
 rows.forEach((r,i)=>{$('row-work-hours-'+i).textContent=!r.enabled?'Ikke inkludert':r.requiresTime?'Beregnet tid venter på grunntid':Number.isFinite(r.quantity*r.hours*r.factor)?num(r.quantity*r.hours*r.factor)+' beregnede timer':'';$('row-work-hours-'+i).title=num(r.quantity)+' '+r.unit+' × '+num(r.hours)+' t/'+r.unit+' × '+num(r.factor);$('row-labor-unit-'+i).textContent=hourly!==null&&!r.requiresTime&&Number.isFinite(r.hours*r.factor)?'Arbeid: '+money(r.hours*r.factor*hourly*(1+rate.laborMarkup/100))+'/'+r.unit:'Arbeidspris venter på grunntid';});
 const ok=valid()&&[...document.querySelectorAll('#rows tr[data-row-index] input[type=number]')].every(e=>!rows[Number(e.closest('tr').dataset.rowIndex)].enabled||e.checkValidity());for(const id of ['save','export'])$(id).disabled=!ok||(id==='export'&&(missing.length>0||missingQuantities.length>0||missingTimes.length>0));
 $('included').replaceChildren();for(const r of rows.filter(r=>r.enabled)){const li=document.createElement('li');li.textContent=r.name;$('included').append(li);}
 for(const kind of ['work','purchase','sale'])$('export-'+kind).disabled=!ok||!rows.some(r=>r.enabled)||(kind!=='purchase'&&missingTimes.length>0)||(kind!=='work'&&missing.length>0)||missingQuantities.length>0;
 $('estimate-kind').textContent='DITT PRISANSLAG';$('estimate-state').textContent='';
 if(!ok){for(const indices of renderedGroups){$('group-total-'+indices[0]).textContent='—';$('group-hours-'+indices[0]).textContent='Beregnet arbeid: —';}result=null;$('status').textContent='Fyll inn gyldige tall i alle feltene før kalkylen beregnes.';for(const id of ['total','per-area','hours','cost','profit','vat','gross','calc-area','labor-total','material-total'])$(id).textContent='—';rows.forEach((r,i)=>$('row-total-'+i).textContent='—');return;}
 const area=lastSettings.job==='roof'?roofGeometry(lastSettings).area:lastSettings.area,calculation=calculate(rows,rate,area);
 for(const indices of renderedGroups){const selected=indices.filter(i=>rows[i].enabled),knownHours=selected.reduce((sum,i)=>sum+(rows[i].requiresTime?0:calculation.items[i].workHours),0);$('group-hours-'+indices[0]).textContent='Beregnet arbeid: '+num(knownHours)+' timer'+(selected.some(i=>rows[i].requiresTime)?' (kjente)':'');}
 $('calc-area').textContent=num(area)+' m²';$('hours').textContent=num(calculation.hours)+' t'+(missingTimes.length||missingQuantities.length?' (kjente)':'');
 const laborPartial=missingTimes.length||missingQuantities.length,materialPartial=missing.length||missingQuantities.length;
 $('labor-total-label').textContent=laborPartial?'Arbeidspris · kjente poster':'Arbeidspris med påslag';$('material-total-label').textContent=materialPartial?'Materialpris · kjente poster':'Materialpris med påslag';
 $('labor-total').textContent=money(calculation.items.reduce((sum,r)=>sum+(r.requiresTime||r.requiresQuantity&&r.quantity===0?0:r.laborPrice),0));$('material-total').textContent=money(calculation.items.reduce((sum,r)=>sum+(r.priceIssue||r.requiresQuantity&&r.quantity===0?0:r.materialPrice),0));
 function totalFor(indices,target){const chosen=indices.filter(i=>rows[i].enabled),problems=[];if(chosen.some(i=>rows[i].requiresQuantity&&rows[i].quantity===0))problems.push('Mengde mangler');if(chosen.some(i=>rows[i].requiresTime))problems.push('Grunntid mangler');if(chosen.some(i=>rows[i].priceIssue))problems.push('Materialpris mangler');target.replaceChildren();
  if(!chosen.length){target.textContent='Ikke inkludert';return;}if(!problems.length){target.textContent=money(chosen.reduce((sum,i)=>sum+calculation.items[i].price,0));return;}
  const known=chosen.reduce((sum,i)=>{const r=calculation.items[i];return sum+(r.requiresQuantity&&r.quantity===0?0:(r.requiresTime?0:r.laborPrice)+(r.priceIssue?0:r.materialPrice));},0);if(known){const amount=document.createElement('strong');amount.textContent=money(known)+' (kjent)';target.append(amount);}const note=document.createElement('small');note.className='price-warning';note.textContent=problems.join(' · ');target.append(note);
 }
 for(const indices of renderedGroups)totalFor(indices,$('group-total-'+indices[0]));rows.forEach((r,i)=>totalFor([i],$('row-total-'+i)));
 if(!rows.some(r=>r.enabled)||missing.length||missingQuantities.length||missingTimes.length){
  result=null;for(const id of ['total','per-area','cost','profit','vat','gross'])$(id).textContent='—';$('export').disabled=true;
  if(rows.some(r=>r.enabled)){const known=calculation.items.reduce((sum,r)=>sum+(r.requiresQuantity&&r.quantity===0?0:(r.requiresTime?0:r.laborPrice)+(r.priceIssue?0:r.materialPrice)),0);$('estimate-kind').textContent='KJENT DELSUM';$('total').textContent=money(known);$('estimate-state').textContent='Ufullstendig prisanslag · ekskl. MVA';}
  $('status').textContent=!rows.some(r=>r.enabled)?'Kalkylen er tom. Legg til bygningselementer og velg oppgavene som skal inngå.':`${missing.length} oppgaver mangler materialpris; ${missingQuantities.length} mangler mengde; ${missingTimes.length} mangler grunntid. Avklar postene i forenkletvisningen eller velg vare på oppgaven. Kjent delsum inkluderer påslag. Manglende poster kommer i tillegg; komplett prisanslag og salgsgrunnlag venter på avklaring.`;return;
 }
 result=calculation;$('estimate-state').textContent='Komplett prisgrunnlag · ekskl. MVA';$('total').textContent=money(result.price);$('per-area').textContent=money(result.perArea)+'/m²';for(const id of ['cost','profit','vat','gross'])$(id).textContent=money(result[id]);$('status').textContent=edited?'Egne postendringer er med i anslaget.':'Forslag fra veiviseren. Kontroller omfang og satser.';
}

function view(detail){calculationMode=detail?'detailed':'simple';workspacePane(calculationMode);}
function workspacePane(pane){document.querySelector('.layout').dataset.pane=pane;for(const [button,panel] of [['simple','wizard'],['detailed','details'],['pricing-tab','pricing-pane'],['rates-tab','rates-pane']]){const selected=button===pane;$(panel).hidden=!selected;$(button).setAttribute('aria-pressed',String(selected));}const text={simple:'Velg arbeidet og avklar omfanget. Veiviseren foreslår poster til kontroll.',detailed:'Bygg kalkylen fra biblioteket. Juster oppgaver, mengder og materialforbruk.', 'pricing-tab':'Velg dokumenterte materialpriser og kontroller kilde, dato og enhet.', 'rates-tab':'Sett prosjektets timekostnad og påslag. Endringene påvirker denne kalkylen.'};$('workspace-view-help').textContent=text[pane];}
$('pricing-tab').onclick=()=>workspacePane('pricing-tab');$('rates-tab').onclick=()=>workspacePane('rates-tab');
$('simple').onclick=()=>view(false);$('detailed').onclick=()=>view(true);
$('questions').onsubmit=e=>e.preventDefault();$('questions').onchange=()=>{if(edited&&!confirm('Endringen lager et nytt forslag og erstatter redigerte poster. Fortsette?')){const s=lastSettings;for(const k of ['area','angle','basis','material','difficulty',...roofKeys])if(s[k]!==undefined)$(k).value=s[k];for(const el of document.querySelectorAll('#options input'))el.checked=s.options.includes(el.value);configureRoof();return;}generate();};
for(const key of rateKeys)$(key).oninput=()=>{edited=true;update();};
function loadRateDefaults(){
 try{const saved=JSON.parse(userStorage.getItem(rateDefaultKey)||'null');if(!saved)return;const previous=rates();if(saved.version!==1||!rateKeys.every(k=>Number.isFinite(saved.rates?.[k])))throw Error();for(const k of rateKeys)$(k).value=saved.rates[k];if(!rateKeys.every(k=>$(k).checkValidity())){for(const k of rateKeys)$(k).value=previous[k];throw Error();}$('rates-status').textContent='Lagrede standardsatser er brukt. Prosjektets egne endringer lagres med kalkylen.';}catch{$('rates-status').textContent='Standardsatsene kunne ikke leses. Kontroller prosjektets satser.';}
}
$('save-rate-defaults').onclick=()=>{
 if(!rateKeys.every(k=>$(k).checkValidity())){$('rates-status').textContent='Fyll inn gyldige satser før du lagrer standarden.';return;}
 try{userStorage.setItem(rateDefaultKey,JSON.stringify({version:1,rates:rates()}));$('rates-status').textContent='Satsene brukes på nye prosjekter for din konto i denne nettleseren. Eksisterende prosjekter beholder sine satser.';saveProject();}catch{$('rates-status').textContent='Standardsatsene kunne ikke lagres. Prosjektets satser er beholdt.';}
};
function downloadCsv(lines,name){const url=URL.createObjectURL(new Blob([csvText(lines)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('time-template').onclick=()=>{
 const unique=[...new Map(rows.map(r=>[r.taskKey||templateTask(r)?.key||r.id,r])).entries()];downloadCsv([['oppgavenokkel','oppgave','enhet','timer_per_enhet','tidsfaktor','kilde'],...unique.map(([key,r])=>[key,r.name,r.unit,'','',''])],'rigor-grunntider-mal.csv');
};
$('time-file').onchange=async()=>{
 const file=$('time-file').files[0];if(!file)return;
 try{if(file.size>2000000)throw Error('Filen er for stor (maks 2 MB).');const imported=parseTimeCsv(await file.text()),next=applyTimeCatalog(rows,imported),count=next.filter((r,i)=>r!==rows[i]).length;if(!count)throw Error('Ingen oppgaver kunne kobles. Kontroller nøkkel, oppgavenavn og enhet. Manuelt registrerte tider beholdes.');timeCatalog=imported;rows=next;edited=true;renderRows();update();saveProject();$('time-status').textContent=count+' oppgaver fikk importert grunntid. Kilden vises på posten; manuelle tider er beholdt.';}catch(error){$('time-status').textContent='Import avvist: '+error.message+' Gjeldende tider er beholdt.';}
 $('time-file').value='';
};
$('reset').onclick=()=>{if(!edited||confirm('Gjenopprette postene fra veiviseren?'))generate();};
$('save').onclick=()=>{try{userStorage.setItem('rigor-calculation-v1',JSON.stringify({version:2,settings:lastSettings,rows,rates:rates(),edited,priceMode,importedPrices,marketPrices,marketBindings,marketStores,timeCatalog}));$('status').textContent='Kalkylen er lagret i denne nettleseren.';}catch{$('status').textContent='Nettleseren tillater ikke lokal lagring. Bruk CSV-eksport.';}};
function restoreCalculation(snapshot=null){try{const raw=snapshot?JSON.stringify(snapshot):userStorage.getItem('rigor-calculation-v1');if(!raw){$('status').textContent='Ingen lokal kalkyle er lagret.';return;}const s=JSON.parse(raw);if(![1,2].includes(s.version)||!jobs[s.settings?.job]||!Array.isArray(s.rows)||s.rows.length>500||s.rows.some(r=>typeof r.name!=='string'||typeof r.enabled!=='boolean'||!['m²','m','stk','rs'].includes(r.unit)||['quantity','material','hours','factor'].some(k=>!Number.isFinite(r[k])||r[k]<0))||!rateKeys.every(k=>Number.isFinite(s.rates?.[k]))||!['surface','footprint'].includes(s.settings.basis)||!['metal','tile','membrane'].includes(s.settings.material)||!Array.isArray(s.settings.options)||!['area','angle','difficulty'].every(k=>Number.isFinite(s.settings[k])))throw Error();if(edited&&!confirm('Erstatte den åpne kalkylen med den lagrede?'))return;
 if(s.version===2){if(!['market','import','example'].includes(s.priceMode)||!Array.isArray(s.importedPrices))throw Error();if(s.importedPrices.length)validatePrices(s.importedPrices);if(s.marketPrices?.length)validatePrices(s.marketPrices);priceMode=s.priceMode;importedPrices=s.importedPrices;marketPrices=s.marketPrices||[];marketBindings=s.marketBindings&&typeof s.marketBindings==='object'&&!Array.isArray(s.marketBindings)?{...s.marketBindings}:{};marketStores=s.marketStores&&typeof s.marketStores==='object'&&!Array.isArray(s.marketStores)?{byggmax:String(s.marketStores.byggmax||'')}:{};syncBoundPrices();if(priceMode==='market'&&marketPrices.length)marketMessage='Lagret prisgrunnlag. Kilde og dato kontrolleres; hent nye priser ved behov.';}else{priceMode='example';importedPrices=[];}
 timeCatalog=validateTimeCatalog(s.timeCatalog??[]);$('time-status').textContent=timeCatalog.length?timeCatalog.length+' importerte grunntider er lagret med prosjektet.':'';$('rates-status').textContent='Kalkylens lagrede timesatser er brukt. Endringer påvirker dette prosjektet.';
 $('price-mode').value=priceMode;
 const restored={roofType:'gable',lowerAngle:60,upperShare:50,ridgeLength:0,hipLength:0,breakLength:0,edgeLength:0,drainCount:0,battenSpacing:600,lathSpacing:500,roofWaste:0,...s.settings};
 job=s.settings.job;setupJob();for(const k of ['area','angle','basis','material','difficulty',...roofKeys])if(restored[k]!==undefined)$(k).value=restored[k];for(const el of document.querySelectorAll('#options input'))el.checked=s.settings.options.includes(el.value);configureRoof();for(const k of rateKeys)$(k).value=s.rates[k];lastSettings=restored;rows=s.rows.map(r=>({...r,materialQuantity:r.materialQuantity??r.quantity,materialUnit:r.materialUnit||r.unit,materialRatio:r.materialRatio??1,priceKey:r.priceKey===undefined&&r.material>0?`${job}.${r.id}${job==='roof'&&r.id==='cover'?'.'+s.settings.material:''}`:r.priceKey,manualPrice:Boolean(r.manualPrice)}));rows=applyTimeCatalog(restoreAssistantTimes(rows,restored),timeCatalog);edited=Boolean(s.edited);renderRows();update();if(result)$('status').textContent='Lokal kalkyle åpnet med lagrede priser. Valgte produkter oppdateres fra det siste innhentede prisregisteret.';
 return true;}catch{$('status').textContent='Kunne ikke åpne lokal kalkyle. Lagrede data er ugyldige eller utilgjengelige.';return false;}}
$('restore').onclick=()=>restoreCalculation();
$('export').onclick=()=>{syncBoundPrices();marketSelectionSignature='';update();if(!result)return;downloadCsv([['RIGOR prisanslag – prisgrunnlag: '+priceMode+', ekskl. MVA; kontroller grunntider og omfang'],['Elementkode','Arbeidskode','Innkjøpskode','Salgskode','Oppgave','Mengde','Enhet','Materiellmengde','Materialenhet','Materiell kr/enhet','Timer/enhet','Tidsfaktor','Arbeidstimer','Arbeidspris ekskl. MVA','Materialpris ekskl. MVA','Kostnad','Pris ekskl. MVA','Priskilde','Prisdato'],...result.items.filter(r=>r.enabled).map(r=>{const c=rowCodes(r);return [c.element,c.work,c.purchase,c.sale,r.name,r.quantity,r.unit,r.materialQuantity,r.materialUnit,r.material,r.hours,r.factor,r.workHours,r.laborPrice,r.materialPrice,r.cost,r.price,r.priceSource,r.priceDate];}),['Totalt','','','','','','','','','','','',result.hours,result.items.reduce((s,r)=>s+r.laborPrice,0),result.items.reduce((s,r)=>s+r.materialPrice,0),result.cost,result.price],['Taktype',lastSettings.job==='roof'?roofTypes[lastSettings.roofType||'gable'].name:''],['Forutsetninger',jobs[job].uncertainty]],'rigor-prisanslag.csv');};
for(const kind of ['work','purchase','sale'])$('export-'+kind).onclick=()=>{update();try{const data=exportBasis({rows,rates:rates(),project:projects.find(p=>p.id===activeProject)||{},offers:publicCatalog?.offers||[],bindings:marketBindings,priceMode},kind);downloadCsv(data,'rigor-'+({work:'arbeidsplan',purchase:'innkjopsgrunnlag',sale:'salgsgrunnlag'}[kind])+'.csv');$('export-basis-status').textContent='Eksportert som generelt CSV-grunnlag. Kobling til regnskapssystem gjøres når systemet er valgt.';}catch(error){$('export-basis-status').textContent=error.message;}};
let codesRowId=null;
function openCodes(id){const row=rows.find(r=>r.id===id);if(!row)return;codesRowId=id;const c=rowCodes(row);$('codes-title').textContent='Koder: '+row.name;$('codes-internal').textContent='Element: '+c.element+' · Oppgavenøkkel: '+row.taskKey;for(const key of ['work','salary','purchase','sale'])$('code-'+key).value=c[key];$('codes-status').textContent='';$('codes-dialog').showModal();}
$('codes-cancel').onclick=()=>$('codes-dialog').close();
$('codes-form').onsubmit=event=>{event.preventDefault();const row=rows.find(r=>r.id===codesRowId);if(!row)return;row.codeMappings=Object.fromEntries(['work','salary','purchase','sale'].map(k=>[k,$('code-'+k).value.trim()]));edited=true;renderRows();update();saveProject();$('codes-dialog').close();};
function applyCatalog(){rows=rows.map(r=>({...r,manualPrice:false}));edited=true;renderRows();update();}
$('price-mode').onchange=()=>{
 const next=$('price-mode').value;
 if(rows.some(r=>r.manualPrice)&&!confirm('Bytte prisgrunnlag erstatter manuelt satte materialpriser. Fortsette?')){$('price-mode').value=priceMode;return;}
 priceMode=next;applyCatalog();
};
$('price-file').onchange=async()=>{
 const file=$('price-file').files[0];if(!file)return;
 try{if(file.size>2_000_000)throw Error('Prislisten er for stor (maks 2 MB).');const prices=parseCsv(await file.text());
 if(rows.some(r=>r.manualPrice)&&!confirm('Import erstatter manuelt satte materialpriser. Fortsette?'))return;
 importedPrices=prices;priceMode='import';$('price-mode').value=priceMode;applyCatalog();
 }catch(error){$('price-status').textContent='Import avvist: '+error.message+' Gjeldende priser er beholdt.';}
 $('price-file').value='';
};
$('template').onclick=()=>{
 const unique=[...new Map(rows.filter(r=>r.priceKey).map(r=>[r.priceKey,r])).values()];const data=['prisnokkel;enhet;pris;kilde;dato;valuta;mva',...unique.map(r=>`${r.priceKey};${(r.materialUnit||r.unit).replace('m²','m2')};;;;NOK;ekskl`)];
 const url=URL.createObjectURL(new Blob(['\uFEFF'+data.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='rigor-prisliste-mal.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
};
function syncBoundPrices(){if(!publicCatalog)return;const selected=selectedPrices(publicCatalog.offers,marketBindings,Date.now(),marketStores).filter(p=>rows.filter(r=>r.priceKey===p.prisnokkel).every(r=>offersForRow(r,publicCatalog.offers,Date.now(),marketStores).some(o=>o.id===marketBindings[p.prisnokkel])));marketPrices=[...marketPrices.filter(p=>!Object.hasOwn(marketBindings,p.prisnokkel)),...selected];}
function chooseMarketProduct(row,id){
 if(id){const offer=offersForRow(row,publicCatalog?.offers||[],Date.now(),marketStores).find(o=>o.id===id);if(!offer)throw Error('Varen har ingen gyldig pris for denne oppgaven og butikken.');marketBindings[row.priceKey]=id;}else delete marketBindings[row.priceKey];
 marketPrices=marketPrices.filter(p=>p.prisnokkel!==row.priceKey);syncBoundPrices();rows.forEach(r=>{if(r.priceKey===row.priceKey)r.manualPrice=false;});marketSelectionSignature='';edited=true;update();saveProject();
}
let materialRowId=null;
function renderMaterialChoices(){
 const row=rows.find(r=>r.id===materialRowId);if(!row)return;
 const target=$('material-product');target.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent='Velg produkt og dimensjon';target.append(blank);
 const candidates=offersForRow(row,publicCatalog?.offers||[],Date.now(),{...marketStores,byggmax:$('material-store').value}).sort((a,b)=>a.name.localeCompare(b.name,'nb'));
 for(const o of candidates){const option=document.createElement('option');option.value=o.id;option.textContent=o.name+' · '+o.chain+(o.store_name?' '+o.store_name:'')+' · '+money(o.normalized_ore/100)+'/'+o.unit+' ekskl. MVA';target.append(option);}
 target.value=candidates.some(o=>o.id===marketBindings[row.priceKey])?marketBindings[row.priceKey]:'';target.disabled=!candidates.length;$('material-submit').disabled=!candidates.length;
 $('material-dialog-note').textContent=candidates.length?'Prisen gjelder '+row.materialUnit+', før materialpåslag. Obs BYGG viser offentlige priser; Byggmax-priser gjelder valgt butikk. Kontroller produkt og bruksområde.':'Prisregisteret har ingen ferske, brukbare priser for denne varetypen i '+row.materialUnit+'. Byggmax-butikken begrenser bare Byggmax-prisene; offentlige Obs BYGG-priser vises også. Oppdater prisvalgene, prøv en annen butikk eller registrer leverandørpris.';
 $('material-product-detail').textContent='';$('material-error').textContent='';
}
async function openMaterialDialog(id){
 const row=rows.find(r=>r.id===id);if(!row)return;materialRowId=id;$('material-dialog-title').textContent='Markedsvare: '+row.name;
 renderMarketStores();$('material-store').replaceChildren(...[...$('byggmax-store').options].map(o=>o.cloneNode(true)));$('material-store').value=marketStores.byggmax||'';$('material-store').disabled=$('byggmax-store').disabled;
 renderMaterialChoices();$('material-dialog').showModal();
 if(!publicCatalog){await refreshMarketPrices();if(!$('material-dialog').open)return;renderMarketStores();$('material-store').replaceChildren(...[...$('byggmax-store').options].map(o=>o.cloneNode(true)));$('material-store').value=marketStores.byggmax||'';$('material-store').disabled=$('byggmax-store').disabled;renderMaterialChoices();}
}
$('material-cancel').onclick=()=>$('material-dialog').close();
$('material-refresh').onclick=async()=>{const staged=$('material-store').value;$('material-refresh').disabled=true;try{await refreshMarketPrices();if(!$('material-dialog').open)return;renderMarketStores();$('material-store').replaceChildren(...[...$('byggmax-store').options].map(o=>o.cloneNode(true)));$('material-store').value=[...$('material-store').options].some(o=>o.value===staged)?staged:marketStores.byggmax||'';$('material-store').disabled=$('byggmax-store').disabled;renderMaterialChoices();}finally{$('material-refresh').disabled=false;}};
$('material-manual').onclick=()=>{const row=rows.find(r=>r.id===materialRowId);$('material-dialog').close();if(!row)return;if(!row.enabled){view(true);document.querySelector(`[data-row-index='${rows.indexOf(row)}'] [data-field=material]`)?.focus();return;}view(false);const task=document.querySelector(`[data-completion-id='${CSS.escape(row.id)}']`);const manual=task?.querySelector('.completion-manual');if(!manual)return;task.closest('.completion-group').open=true;manual.open=true;manual.querySelector('input')?.focus();};
$('material-store').onchange=renderMaterialChoices;
$('material-product').onchange=()=>{const offer=publicCatalog?.offers.find(o=>o.id===$('material-product').value);$('material-product-detail').textContent=offer?offer.chain+(offer.store_name?' '+offer.store_name:'')+' · Kontrollert '+new Date(offer.checked_at).toLocaleString('nb-NO')+' · '+money(offer.normalized_ore/100)+'/'+offer.unit+' ekskl. MVA. '+(offer.quantity_basis==='package'?'Kjøp avrundes opp til hele '+(offer.original_unit==='rull'?'ruller':'pakninger')+'. ':'')+(offer.package_area_basis==='gross'?num(offer.package_quantity)+' m² brutto per rull. Legg til overlapp og svinn i materiellmengden. ':'')+'Frakt er ikke inkludert.':'';};
$('material-form').onsubmit=event=>{event.preventDefault();const row=rows.find(r=>r.id===materialRowId);if(!row)return;try{if(!offersForRow(row,publicCatalog?.offers||[],Date.now(),{...marketStores,byggmax:$('material-store').value}).some(o=>o.id===$('material-product').value))throw Error('Varen har ingen gyldig pris. Velg på nytt.');if($('byggmax-store').value!==$('material-store').value){$('byggmax-store').value=$('material-store').value;$('byggmax-store').dispatchEvent(new Event('change'));}chooseMarketProduct(row,$('material-product').value);$('material-dialog').close();}catch(error){$('material-error').textContent=error.message;}};
function renderMarketStores(){
 const select=$('byggmax-store');const stores=(publicCatalog?.stores||[]).filter(s=>s.chain==='byggmax');const signature=JSON.stringify([stores,marketStores.byggmax]);if(select.dataset.signature===signature)return;select.dataset.signature=signature;select.replaceChildren();const blank=document.createElement('option');blank.value='';blank.textContent='Velg butikk for lokale Byggmax-priser';select.append(blank);for(const s of stores){const option=document.createElement('option');option.value=s.id;option.textContent=s.name;select.append(option);}if(marketStores.byggmax&&!stores.some(s=>s.id===marketStores.byggmax)){const option=document.createElement('option');option.value=marketStores.byggmax;option.disabled=true;option.textContent='Lagret butikk har ingen kontrollerte priser';select.append(option);}select.value=marketStores.byggmax||'';select.disabled=!stores.length;
}
$('byggmax-store').onchange=()=>{marketStores.byggmax=$('byggmax-store').value;for(const [key,id] of Object.entries(marketBindings)){const old=publicCatalog?.offers.find(o=>o.id===id);if(old?.chain!=='byggmax'||!old.store_id)continue;const peer=publicCatalog.offers.find(o=>o.chain===old.chain&&o.source_id===old.source_id&&o.store_id===marketStores.byggmax&&['name','unit','package_quantity','quantity_basis'].every(k=>o[k]===old[k])&&usableOffer(o));if(peer)marketBindings[key]=peer.id;marketPrices=marketPrices.filter(p=>p.prisnokkel!==key);}syncBoundPrices();marketSelectionSignature='';edited=true;update();saveProject();};
function renderMarketProducts(){
 renderMarketStores();const target=$('market-products');if(!target)return;const unique=[...new Map(rows.filter(r=>r.enabled&&r.priceKey).map(r=>[r.priceKey,r])).values()];const signature=JSON.stringify([unique.map(r=>[r.priceKey,r.name,r.materialUnit,r.unit]),marketBindings,marketStores,publicCatalog?.updated_at]);if(signature===marketSelectionSignature)return;marketSelectionSignature=signature;target.replaceChildren();if(!publicCatalog?.offers.length)return;
 const heading=document.createElement('h3');heading.textContent='Velg produkt til materialpostene';target.append(heading);const note=document.createElement('p');note.className='muted';note.textContent='Kontroller dimensjon, kvalitet og bruksområde. Valget lagres med prosjektet og følger samme produkt ved oppdatering.';target.append(note);
 for(const row of unique){const candidates=offersForRow(row,publicCatalog.offers,Date.now(),marketStores).sort((a,b)=>a.name.localeCompare(b.name,'nb'));if(!candidates.length&&!marketBindings[row.priceKey]){const note=document.createElement('p');note.className='price-warning';note.textContent=row.name+': ingen kontrollerte priser med riktig enhet ('+row.materialUnit+') i valgt butikk. Importer eller registrer innkjøpsprisen.';target.append(note);continue;}const label=document.createElement('label');label.textContent=row.name;const select=document.createElement('select');select.dataset.marketKey=row.priceKey;select.setAttribute('aria-label','Markedsprodukt: '+row.name);const blank=document.createElement('option');blank.value='';blank.textContent='Velg konkret produkt og dimensjon';select.append(blank);for(const o of candidates){const option=document.createElement('option');option.value=o.id;option.textContent=o.name+' · '+o.chain+(o.store_name?' '+o.store_name:'')+' · '+money(o.normalized_ore/100)+'/'+o.unit+' ekskl. MVA';select.append(option);}const chosen=marketBindings[row.priceKey];if(chosen&&!candidates.some(o=>o.id===chosen)){const option=document.createElement('option');option.value=chosen;option.disabled=true;option.textContent='Valgt produkt er ikke tilgjengelig med gyldig pris';select.append(option);}select.value=chosen||'';select.onchange=()=>{try{chooseMarketProduct(row,select.value);}catch(error){$('price-status').textContent=error.message;}};label.append(select);target.append(label);}
}
async function refreshMarketPrices(){
 const request=++priceRequest;$('refresh-prices').disabled=true;marketMessage='Henter kontrollerte produktpriser …';update();
 try{const data=await loadPublicCatalog();if(request!==priceRequest)return;publicCatalog=data;syncBoundPrices();const usable=data.offers.filter(o=>usableOffer(o));marketMessage=data.last_run?usable.length+' ferske produktpriser. Siste prisjobb: '+new Date(data.last_run.finished_at).toLocaleString('nb-NO')+'. Velg varer nedenfor. Frakt er ikke inkludert.':'Prisjobben har ikke publisert leverandørpriser ennå.';const errors=data.sources.filter(s=>s.error||s.checked&&!s.succeeded&&!usable.some(o=>o.chain===s.chain));if(errors.length)marketMessage+=' Kildekontroll: '+errors.map(s=>s.chain+' – '+(s.error?'kildedata var ikke tilgjengelige.':'ingen brukbare priser i siste kontroll; prisgrunnlaget kunne ikke bekreftes.')).join(' ');if(data.last_run&&!usable.length)marketMessage+=' Ingen priser kan brukes før kilde, enhet, MVA og lager er bekreftet.';marketSelectionSignature='';update();}
 catch(e){marketMessage=e.message+' Tidligere priser beholder kontrolltiden og utløper etter 24 timer.';update();}
 finally{$('refresh-prices').disabled=false;}
}
$('refresh-prices').onclick=refreshMarketPrices;
loadRateDefaults();setupJob();generate();

let importFile=null,importGeneration=0,importClient=null;
const fieldNames={prisnokkel:'Prisnøkkel (RIGOR-post)',enhet:'Enhet',pris:'Innkjøpspris',kilde:'Leverandør / kilde',dato:'Prisdato',valuta:'Valuta',mva:'MVA-grunnlag'};
function currentMapping(){return Object.fromEntries(fields.map(k=>[k,$('map-'+k).value===''?null:Number($('map-'+k).value)]));}
function importDefaults(){return {kilde:$('default-source').value.trim(),dato:$('default-date').value,valuta:'NOK',enhet:'m2',mva:'ekskl'};}
function previewMapping(){
 $('mapping-confirm').checked=false;$('confirm-import').disabled=true;
 const mapping=currentMapping(),defaults=importDefaults();$('mapping-preview').replaceChildren();
 for(const row of importFile.records.slice(0,5)){const tr=document.createElement('tr');for(const k of fields){const td=document.createElement('td');td.textContent=mapping[k]===null?defaults[k]||'Mangler':row[mapping[k]];tr.append(td);}$('mapping-preview').append(tr);}
}
function renderMapping(mapping){
 checkMapping(mapping,importFile.headers.length);$('mapping-fields').replaceChildren();
 for(const k of fields){const label=document.createElement('label');label.textContent=fieldNames[k];const select=document.createElement('select');select.id='map-'+k;const empty=document.createElement('option');empty.value='';empty.textContent='Ingen kolonne – fyll inn / avklar';select.append(empty);
 importFile.headers.forEach((title,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${i+1}: ${title}`;select.append(option);});select.value=mapping[k]===null?'':mapping[k];select.onchange=previewMapping;label.append(select);$('mapping-fields').append(label);}
 $('mapping-head').replaceChildren();const tr=document.createElement('tr');for(const k of fields){const th=document.createElement('th');th.textContent=fieldNames[k];tr.append(th);}$('mapping-head').append(tr);previewMapping();
}
$('assist-file').onchange=async()=>{
 const generation=++importGeneration;importFile=null;$('mapping-panel').hidden=true;const file=$('assist-file').files[0];if(!file)return;
 try{if(file.size>2_000_000)throw Error('Filen er for stor (maks 2 MB).');const prepared=prepareImport(await file.text());if(generation!==importGeneration)return;importFile=prepared;$('mapping-panel').hidden=false;$('ai-import-status').textContent='Kolonner er foreslått med faste regler. Kontroller koblingen eller be AI om hjelp.';$('sample-info').textContent=`${prepared.records.length} rader og ${prepared.headers.length} kolonner. Originalfilen beholdes i nettleseren frem til import.`;renderMapping(prepared.mapping);}
 catch(error){$('price-status').textContent='Analyse avvist: '+error.message;}
};
for(const id of ['default-source','default-date'])$(id).oninput=()=>{if(importFile)previewMapping();};
$('mapping-confirm').onchange=()=>{$('confirm-import').disabled=!$('mapping-confirm').checked;};
$('confirm-import').onclick=()=>{
 if(!importFile||!$('mapping-confirm').checked)return;
 try{const prices=mapImport(importFile,currentMapping(),importDefaults());if(rows.some(r=>r.manualPrice)&&!confirm('Import erstatter manuelt satte materialpriser. Fortsette?'))return;
 importedPrices=prices;priceMode='import';$('price-mode').value=priceMode;applyCatalog();$('ai-import-status').textContent=`${prices.length} priser importert etter din bekreftelse. Kilde og dato følger prisene.`;$('mapping-confirm').checked=false;$('confirm-import').disabled=true;
 }catch(error){$('ai-import-status').textContent='Import avvist: '+error.message+' Gjeldende priser er beholdt.';}
};
$('ai-map').onclick=async()=>{
 if(!importFile)return;
 let sample;try{sample=sampleImport(importFile);}catch(error){$('ai-import-status').textContent=error.message;return;}
 const generation=importGeneration;
 if(!confirm('Sende kolonneoverskrifter og opptil åtte rader til OpenAI for kolonneforslag? Se forhåndsvisningen før du fortsetter.'))return;
 $('ai-map').disabled=true;$('ai-import-status').textContent='Analyserer kolonner …';
 try{
  if(!importClient)importClient=await getPortalClient();
  const {data,error}=await importClient.auth.getSession();if(error||!data.session)throw Error('Logg inn som administrator i portalen først. Manuell kolonneimport fungerer uten AI.');
  const response=await fetch('https://hyqiqjuycivihsgjongj.supabase.co/functions/v1/rigor-import-map',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token,apikey:'sb_publishable_Y5qghQsmaJZEXYhwxgH6Eg_TjPiWOBl'},body:JSON.stringify(sample),signal:AbortSignal.timeout(30000)});
  const answer=await response.json();if(!response.ok)throw Error(answer.error||'AI-import er ikke aktivert i Supabase ennå.');if(generation!==importGeneration)return;
  renderMapping(checkMapping(answer.mapping,importFile.headers.length));$('ai-import-status').textContent=`AI-forslag klart. Kontroller alle felt før import. Forbruk: ${answer.usage?.input_tokens||0} input-tokens og ${answer.usage?.output_tokens||0} output-tokens.`;
 }catch(error){if(generation===importGeneration)$('ai-import-status').textContent=error.message+' Ingen priser er endret.';}
 finally{$('ai-map').disabled=false;}
};

let localLibrary=[];
try{
 const raw=userStorage.getItem('rigor-library-v1');if(raw&&raw.length<1_000_000){const data=JSON.parse(raw);
 if(Array.isArray(data)&&data.length<=100&&data.every(e=>typeof e.id==='string'&&typeof e.name==='string'&&typeof e.category==='string'&&['m²','m','stk','rs'].includes(e.unit)&&Array.isArray(e.tasks)&&e.tasks.length<=100&&e.tasks.every(t=>typeof t.id==='string'&&typeof t.name==='string'&&Number.isFinite(t.hours)&&t.hours>=0&&Number.isFinite(t.materialRatio)&&t.materialRatio>=0&&['m²','m','stk','rs'].includes(t.materialUnit)&&(!t.priceKey||typeof t.priceKey==='string'))))localLibrary=data;
 }}catch{$('library-status').textContent='Lokalt bibliotek kunne ikke leses. RIGOR-malene er fortsatt tilgjengelige.';}
function renderLibrary(){
 const elements=$('library-source').value==='local'?localLibrary:library;
 const old=$('library-category').value;$('library-category').replaceChildren();for(const category of ['Alle',...[...new Set(elements.map(e=>e.category))].sort((a,b)=>a.localeCompare(b,'nb',{numeric:true}))]){const o=document.createElement('option');o.textContent=category;$('library-category').append(o);}if([...$('library-category').options].some(o=>o.value===old))$('library-category').value=old;
 const matches=searchLibrary(elements,{search:$('library-search').value,trade:$('library-trade').value,type:$('library-type').value,category:$('library-category').value});matches.sort((a,b)=>a.category.localeCompare(b.category,'nb',{numeric:true}));$('library-list').replaceChildren();
 let category='',group;for(const element of matches){if(element.category!==category){group=document.createElement('details');group.className='library-category-group';group.open=Boolean($('library-search').value.trim()||$('library-category').value!=='Alle');const heading=document.createElement('summary');heading.textContent=element.category+' ('+matches.filter(e=>e.category===element.category).length+' elementer)';group.append(heading);$('library-list').append(group);category=element.category;}
 const card=document.createElement('details');card.className='library-card';const summary=document.createElement('summary');summary.textContent=`${codesFor(element.id,element.tasks[0].id).element} · ${element.name} (${element.tasks.length} oppgaver)`;card.append(summary);const note=document.createElement('p');note.className='muted';note.textContent=`${element.trade} · ${element.type} · arbeidsenhet ${element.unit}. ${element.tasks.some(t=>t.requiresTime)?'Grunntid må registreres etter at oppgavene er lagt inn.':'Grunntider og forbruk er foreløpige.'} Kontroller faktisk oppbygging og materialvalg.`;card.append(note);
 const scope=document.createElement('dl');scope.className='library-scope';for(const [title,value] of [['Inkluderer',element.description||element.tasks.map(t=>t.name).join(', ')],['Mengdegrunnlag',element.quantityNote||'Oppgi mengde i '+element.unit+'.'],['Ikke inkludert',element.excludes||'Kontroller avgrensningene før kalkylen brukes.']]){const dt=document.createElement('dt');dt.textContent=title;const dd=document.createElement('dd');dd.textContent=value;scope.append(dt,dd);}card.append(scope);
 for(const t of element.tasks){const label=document.createElement('label');label.className='check';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.value=t.id;label.append(checkbox,document.createTextNode(`${t.name} · ${t.requiresTime?'grunntid må registreres':num(t.hours)+' t/'+element.unit}${t.priceKey?' · '+t.materialUnit+' materiell':''} · ${codesFor(element.id,t.id).work}`));card.append(label);}
 const controls=document.createElement('div');controls.className='library-controls';const label=document.createElement('label');label.textContent='Elementmengde ('+element.unit+')';const input=document.createElement('input');input.type='number';input.min='.1';input.max='100000';input.step='any';input.value=element.unit==='m²'?String(job==='roof'?roofGeometry(lastSettings).area:lastSettings.area):'1';input.required=true;input.setAttribute('aria-label','Bibliotekmengde '+element.name);label.append(input);controls.append(label);const add=document.createElement('button');add.textContent='Legg til valgte oppgaver';add.onclick=()=>{
 const selected=[...card.querySelectorAll('input[type=checkbox]:checked')].map(e=>e.value);if(!selected.length||!input.checkValidity()){$('library-status').textContent='Velg minst én oppgave og en positiv mengde.';return;}
 if(rows.length+selected.length>500){$('library-status').textContent='Maks 500 oppgaver i én kalkyle.';return;}
 const factor=timeFactor(element,lastSettings);
 rows.push(...applyTimeCatalog(instantiate(element,Number(input.value),factor,selected,'-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)).map(r=>roofConsumption(r,lastSettings)),timeCatalog));edited=true;renderRows();update();$('library-status').textContent=selected.length+' oppgaver lagt til fra '+element.name+'.';
 };controls.append(add);card.append(controls);group.append(card);}
 if(!matches.length){const p=document.createElement('p');p.className='muted';p.textContent=elements.length?'Ingen elementer samsvarer med filtrene.':'Biblioteket er tomt. Lagre kalkylen som egne elementmaler.';$('library-list').append(p);}
}
for(const id of ['library-source','library-trade','library-type','library-category'])$(id).onchange=renderLibrary;
$('library-search').oninput=renderLibrary;
$('library-browser').ontoggle=()=>{if($('library-browser').open){renderLibrary();if(!$('library-dialog').open)$('library-dialog').showModal();}else if($('library-dialog').open)$('library-dialog').close();};
$('library-dialog').onclose=()=>{$('library-browser').open=false;};
for(const id of ['library-close','library-done'])$(id).onclick=()=>$('library-dialog').close();
new MutationObserver(()=>{$('library-dialog-status').textContent=$('library-status').textContent;}).observe($('library-status'),{childList:true,subtree:true,characterData:true});
$('save-library').onclick=()=>{
 if(!valid()||!rows.some(r=>r.enabled)){$('library-status').textContent='Velg oppgaver og fyll inn gyldige mengder og timer før lagring.';return;}
 const name=prompt('Navn på ditt bibliotek / malsett:',jobs[job].name);if(!name?.trim())return;
 const added=renderedGroups.filter(indices=>indices.some(i=>rows[i].enabled)).map((indices,n)=>{const first=rows[indices[0]];return {id:'local.'+Date.now()+'.'+n,name:name.trim().slice(0,80)+' / '+(first.elementName||first.name),category:first.category||'Egne elementer',trade:'Alle',type:'Alle',unit:first.unit,description:first.elementDescription||'',quantityNote:first.quantityNote||'',excludes:first.excludes||'',tasks:indices.filter(i=>rows[i].enabled).map((i,j)=>{const r=rows[i];return {id:String(j),name:r.name,hours:r.hours,requiresTime:Boolean(r.requiresTime),timeSource:r.timeSource||'',timeEstimate:Boolean(r.timeEstimate),timeNote:r.timeNote||'',priceKey:r.priceKey||null,exampleMaterial:0,materialRatio:r.materialRatio??1,materialUnit:r.materialUnit||r.unit};})};});
 if(localLibrary.length+added.length>100){$('library-status').textContent='Maks 100 egne elementmaler.';return;}
 try{const next=[...localLibrary,...added];userStorage.setItem('rigor-library-v1',JSON.stringify(next));localLibrary=next;$('library-status').textContent=added.length+' elementmaler lagret lokalt. Prisene hentes fra prisgrunnlaget ved bruk; manuelle priser er ikke lagret i malene.';$('library-source').value='local';$('library-trade').value='Alle';$('library-type').value='Alle';$('library-search').value='';renderLibrary();}
 catch{$('library-status').textContent='Nettleseren tillater ikke lagring av biblioteket.';}
};
renderLibrary();

// Project management is local; calculation snapshots keep each project's prices and rates separate.
const newProjectDefaults=projectSnapshot();
const projectKey='rigor-projects-v1';let projects=[],activeProject=null,pendingMode='simple',editingProject=false,briefProjectId=null;
try{const stored=JSON.parse(userStorage.getItem(projectKey)||'[]');if(Array.isArray(stored)&&stored.length<=100)projects=stored.filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&p.snapshot);else throw Error();}catch{$('project-message').textContent='Prosjektlisten kunne ikke leses. Lagrede data er ikke overskrevet.';}
function projectSnapshot(){return {version:2,settings:structuredClone(lastSettings),rows:structuredClone(rows),rates:rates(),edited,priceMode,importedPrices:structuredClone(importedPrices),marketPrices:structuredClone(marketPrices),marketBindings:structuredClone(marketBindings),marketStores:structuredClone(marketStores),timeCatalog:structuredClone(timeCatalog)};}
function persistProjects(){userStorage.setItem(projectKey,JSON.stringify(projects));}
function projectHeader(){const p=projects.find(p=>p.id===activeProject);if(!p)return;$('project-title').textContent=p.name;$('project-meta').textContent=[p.customer,p.address,p.number?'Nr. '+p.number:'',p.state].filter(Boolean).join(' · ');}
function saveProject(){if(!activeProject)return true;const index=projects.findIndex(p=>p.id===activeProject);const previous=projects[index];projects[index]={...previous,snapshot:projectSnapshot(),brief:$('job-brief').value,mode:calculationMode,updated:new Date().toISOString(),total:result?.price??null};try{persistProjects();return true;}catch{projects[index]=previous;$('status').textContent='Prosjektet kunne ikke lagres. Nettleserens lagringsplass kan være full.';return false;}}
function deleteProject(id){
 const project=projects.find(p=>p.id===id);if(!project||!confirm('Slette prosjektet «'+project.name+'»? Kalkylen og prosjektopplysningene fjernes fra denne nettleseren.'))return;
 const previous=projects;projects=projects.filter(p=>p.id!==id);try{persistProjects();}catch{projects=previous;$('project-message').textContent='Prosjektet kunne ikke slettes. Lagrede data er beholdt.';return;}
 renderProjects();const undo=document.createElement('button');undo.type='button';undo.className='secondary';undo.textContent='Angre sletting';
 undo.onclick=()=>{if(projects.some(p=>p.id===id))return;if(projects.length>=100){$('project-message').firstChild.textContent='Maks 100 prosjekter. Fjern et annet prosjekt før du angrer. ';return;}const beforeUndo=projects;projects=[...projects,project];try{persistProjects();}catch{projects=beforeUndo;$('project-message').firstChild.textContent='Slettingen kunne ikke angres. Prøv igjen. ';return;}$('project-message').textContent='Prosjektet «'+project.name+'» er gjenopprettet.';renderProjects();[...$('project-list').children].find(card=>card.dataset.projectId===id)?.querySelector('button')?.focus();};
 $('project-message').replaceChildren(document.createTextNode('Prosjektet «'+project.name+'» er slettet. '),undo);undo.focus();
}
function renderProjects(){const list=$('project-list');list.replaceChildren();const needle=$('project-search').value.toLocaleLowerCase('nb');const matches=projects.filter(p=>[p.name,p.customer,p.address,p.number].join(' ').toLocaleLowerCase('nb').includes(needle)).sort((a,b)=>b.updated.localeCompare(a.updated));for(const p of matches){const card=document.createElement('article');card.className='project-card';card.dataset.projectId=p.id;const title=document.createElement('h3');title.textContent=p.name;const meta=document.createElement('p');meta.textContent=[p.customer,p.address,p.state].filter(Boolean).join(' · ');const detail=document.createElement('p');detail.className='muted';detail.textContent=(p.mode==='detailed'?'Detaljert':'Forenklet')+' · Oppdatert '+new Date(p.updated).toLocaleDateString('nb-NO')+' · '+(p.total===null?'Prisgrunnlag ufullstendig':money(p.total)+' ekskl. MVA');const open=document.createElement('button');open.textContent='Åpne prosjekt';open.onclick=()=>{edited=false;if(!restoreCalculation(p.snapshot)){$('project-message').textContent='Prosjektet kunne ikke åpnes. Kalkyledata må kontrolleres.';return;}activeProject=p.id;view(p.mode==='detailed');showWorkspace();};const remove=document.createElement('button');remove.type='button';remove.className='project-delete';remove.textContent='Slett prosjekt';remove.setAttribute('aria-label','Slett prosjekt '+p.name);remove.onclick=()=>deleteProject(p.id);const actions=document.createElement('div');actions.className='project-card-actions';actions.append(open,remove);card.append(title,meta,detail,actions);list.append(card);}if(!matches.length){const empty=document.createElement('p');empty.className='muted';empty.textContent=projects.length?'Ingen prosjekter samsvarer med søket.':'Ingen prosjekter ennå. Velg Forenklet eller Detaljert for å komme i gang.';list.append(empty);}}
function showWorkspace(){$('project-home').hidden=true;$('project-workspace').hidden=false;projectHeader();$('workspace-brief-anchor').append($('job-composer'));if(briefProjectId!==activeProject){clearAssistantProposal();const brief=projects.find(p=>p.id===activeProject)?.brief;$('job-brief').value=typeof brief==='string'?brief.slice(0,8000):'';briefProjectId=activeProject;}$('brief-status').textContent='Beskrivelsen lagres med prosjektet. Kontroller AI-forslaget før du legger til oppgaver.';window.scrollTo(0,0);}
function projectDialog(mode,edit=false){pendingMode=mode;editingProject=edit;const p=edit?projects.find(p=>p.id===activeProject):null;$('project-name').value=p?.name||'';$('project-customer').value=p?.customer||'';$('project-address').value=p?.address||'';$('project-number').value=p?.number||String(projects.length+1);$('project-state').value=p?.state||'Utkast';$('project-dialog-title').textContent=edit?'Prosjektdetaljer':'Opprett '+(mode==='simple'?'forenklet':'detaljert')+' prosjekt';$('project-submit').textContent=edit?'Lagre detaljer':'Opprett prosjekt';$('project-form-error').textContent='';$('project-dialog').showModal();$('project-name').focus();}
$('start-simple').onclick=()=>projectDialog('simple');$('start-detailed').onclick=()=>projectDialog('detailed');$('project-edit').onclick=()=>projectDialog(calculationMode,true);$('project-cancel').onclick=()=>$('project-dialog').close();$('project-search').oninput=renderProjects;
$('project-form').onsubmit=e=>{e.preventDefault();const name=$('project-name').value.trim();if(!name){$('project-form-error').textContent='Skriv inn et prosjektnavn.';return;}if(!editingProject&&projects.length>=100){$('project-form-error').textContent='Maks 100 lokale prosjekter.';return;}const previous=projects.slice();const previousActive=activeProject;const metadata={name,customer:$('project-customer').value.trim(),address:$('project-address').value.trim(),number:$('project-number').value.trim(),state:$('project-state').value,...(!editingProject?{brief:$('job-brief').value}:{})};if(editingProject){projects=projects.map(p=>p.id===activeProject?{...p,...metadata,updated:new Date().toISOString()}:p);}else{edited=false;restoreCalculation(newProjectDefaults);loadRateDefaults();generate();if(pendingMode==='detailed'){rows=[];edited=true;renderRows();update();}view(pendingMode==='detailed');activeProject=crypto.randomUUID();projects.push({...metadata,id:activeProject,mode:pendingMode,updated:new Date().toISOString(),snapshot:projectSnapshot(),total:result?.price??null});}try{persistProjects();}catch{projects=previous;activeProject=previousActive;$('project-form-error').textContent='Kunne ikke lagre prosjektet i nettleseren.';return;}$('project-dialog').close();showWorkspace();if(pendingMode==='detailed'&&!editingProject)renderLibrary();};
const legacySave=$('save').onclick;$('save').textContent='Lagre prosjekt';$('save').onclick=()=>{if(saveProject()){legacySave();$('status').textContent='Prosjektet er lagret i denne nettleseren.';}};
$('project-back').onclick=()=>{if(!saveProject())return;$('project-workspace').hidden=true;$('project-home').hidden=false;clearAssistantProposal();activeProject=null;briefProjectId=null;$('home-brief-anchor').append($('job-composer'));restoreBriefDraft();renderProjects();window.scrollTo(0,0);};
renderProjects();
try{$('legacy-projects').hidden=!userStorage.hasLegacyData();}catch{$('project-message').textContent='Kontolagringen kunne ikke kontrolleres. Lagrede data er beholdt.';}
$('legacy-import').onclick=()=>{try{if(userStorage.importLegacy())location.reload();else{$('legacy-projects').hidden=true;$('project-message').textContent='Ingen eldre data å overføre.';}}catch(error){$('legacy-import-status').textContent=error.message||'Overføringen kunne ikke lagres. Eldre data og kontodata er beholdt.';}};

const briefDraftKey='rigor-job-brief-v1';
const briefExamples={roof:'Jeg skal bygge et saltak med 30 graders takvinkel og 100 m² målt takflate. Tilbudet skal inkludere takstein, sløyfer, sutak, vindskier, beslag og takrenner.',insulation:'Jeg skal etterisolere ytterveggene. Ta med riving av eksisterende kledning, utlekting, isolasjon, vindsperre og ny kledning. Mengder og tykkelse må avklares.',terrace:'Jeg skal bygge en terrasse. Ta med fundamenter, bjelkelag, terrassebord, festemidler og rekkverk. Areal, høyde og dimensjoner må avklares.'};
function restoreBriefDraft(){try{$('job-brief').value=userStorage.getItem(briefDraftKey)||'';}catch{$('job-brief').value='';}$('brief-status').textContent='Beskrivelsen lagres lokalt. AI-forslag legges aldri automatisk inn i kalkylen.';}
for(const button of document.querySelectorAll('[data-brief-example]'))button.onclick=()=>{if($('job-brief').value.trim()&&!confirm('Erstatte beskrivelsen med dette eksemplet?'))return;clearAssistantProposal();$('job-brief').value=briefExamples[button.dataset.briefExample];$('job-brief').focus();$('brief-status').textContent='Eksempel lagt inn. Tilpass beskrivelsen og lagre den.';};
$('job-brief').oninput=()=>{clearAssistantProposal();$('brief-status').textContent='Beskrivelsen er endret. Velg Lagre beskrivelse for å beholde endringen.';};
$('brief-save').onclick=()=>{try{if(activeProject){if(!saveProject())throw Error('Prosjektet kunne ikke lagres.');}else userStorage.setItem(briefDraftKey,$('job-brief').value);$('brief-status').textContent=activeProject?'Beskrivelsen er lagret med prosjektet.':'Beskrivelsen er lagret lokalt og følger med når du oppretter prosjektet.';}catch(e){$('brief-status').textContent=e.message||'Nettleseren tillater ikke lokal lagring.';}};
$('nav-projects').onclick=()=>{if(activeProject)$('project-back').click();else window.scrollTo({top:0,behavior:'smooth'});};
restoreBriefDraft();

function clearAssistantProposal(){assistantTicket++;assistantProposal=null;assistantClarifications=[];$('assistant-clarification').hidden=true;$('assistant-preview').hidden=true;$('assistant-items').replaceChildren();$('assistant-apply').disabled=false;}
function renderAssistantProposal(proposal,brief){
 const measurements=extractMeasurements(brief);assistantProposal={...proposal,measurements,brief,projectId:activeProject,fromWizard:assistantWizardReview};$('assistant-summary').textContent=proposal.summary;$('assistant-measurements').textContent=[measurements.roofType?roofTypes[measurements.roofType].name:'',measurements.area!==null?num(measurements.area)+' m²':'',measurements.angle!==null?num(measurements.angle)+'°':'',measurements.roofType?(measurements.basis==='surface'?'Oppgitt takflate':measurements.basis==='footprint'?'Horisontalt areal':'Arealgrunnlag må avklares'):''].filter(Boolean).join(' · ');
 $('assistant-items').replaceChildren();for(const item of proposal.items){const e=library.find(e=>e.id===item.elementId);const card=document.createElement('article');card.className='assistant-item';card.dataset.elementId=e.id;const label=document.createElement('label');label.className='check';const selected=document.createElement('input');selected.type='checkbox';selected.dataset.assistantElement='';const exists=rows.some(r=>r.elementId===e.id||r.elementId?.startsWith(e.id+'-'));selected.checked=item.scope!=='optional'&&!exists;label.append(selected,document.createTextNode(e.name));card.append(label);const scope=document.createElement('p');scope.textContent=({requested:'Ønsket arbeid',related:'Tilhørende arbeid – vurder behovet',optional:'Valgfritt tillegg'}[item.scope])+(exists?' · Finnes allerede i kalkylen':'');scope.className='muted';const reason=document.createElement('p');reason.textContent=item.reason;card.append(scope,reason);for(const id of item.taskIds){const t=e.tasks.find(t=>t.id===id);const l=document.createElement('label');l.className='check';const check=document.createElement('input');check.type='checkbox';check.dataset.assistantTask=id;check.checked=true;l.append(check,document.createTextNode(t.name));card.append(l);}const q=document.createElement('label');q.textContent='Mengde ('+e.unit+')';const input=document.createElement('input');input.type='number';input.min='0';input.max='1000000';input.step='any';input.dataset.assistantQuantity='';input.placeholder='Må avklares';input.setAttribute('aria-label','Forslagsmengde '+e.name);if(e.id.startsWith('roof.')&&e.unit==='m²'&&measurements.area!==null){if(measurements.basis==='surface')input.value=measurements.area;else if(measurements.basis==='footprint'&&measurements.angle!==null&&measurements.roofType&&measurements.roofType!=='mansard')input.value=roofGeometry({...lastSettings,...measurements}).area;}else if(assistantWizardReview&&e.unit==='m²'&&job==='insulation'&&e.id.startsWith('insulation.'))input.value=lastSettings.area;else{const terraceArea=terraceProposalArea(e,brief,measurements);if(terraceArea!==null)input.value=terraceArea;}q.append(input);card.append(q);$('assistant-items').append(card);}
 $('assistant-questions').replaceChildren();const heading=document.createElement('h4');heading.textContent='Dette må avklares';$('assistant-questions').append(heading);const allQuestions=[...proposal.questions,...(measurements.roofType&&measurements.area!==null&&!measurements.basis?['Gjelder arealet målt takflate eller horisontalt projisert areal?']:[])];const list=document.createElement('ul');for(const question of allQuestions){const li=document.createElement('li');li.textContent=question;list.append(li);}if(!list.childElementCount){const li=document.createElement('li');li.textContent='Kontroller oppbygging, materialspesifikasjoner, mengder og arbeidstid.';list.append(li);}$('assistant-questions').append(list);
 if(allQuestions.length){const form=document.createElement('form');form.className='assistant-answer-form';const fields=document.createElement('div');fields.className='assistant-clarification-fields';const questions=followupFields(allQuestions,brief);renderClarificationFields(fields,questions);const button=document.createElement('button');button.type='submit';button.textContent='Oppdater forslag med svarene';form.append(fields,button);list.remove();form.onsubmit=event=>{event.preventDefault();continueWithAnswers(questions,fields);};$('assistant-questions').append(form);}
 $('assistant-settings-label').hidden=!(measurements.roofType&&measurements.roofType!=='mansard'&&measurements.area!==null&&measurements.angle!==null&&measurements.basis&&(measurements.roofType!=='flat'||measurements.angle<=5));$('assistant-use-settings').checked=Boolean(!$('assistant-settings-label').hidden&&!rows.length);$('assistant-apply').disabled=!proposal.items.length;$('assistant-preview').hidden=false;
}
async function generateAssistant(skipClarification=false){
 if(!assistantReady||assistantBusy)return;if(!activeProject){projectDialog('detailed');$('project-form-error').textContent='Opprett prosjektet først. Beskrivelsen følger med.';return;}const brief=$('job-brief').value.trim();if(brief.length<10){$('brief-status').textContent='Skriv minst ti tegn om jobben.';return;}if(!saveProject())return;
 if(!skipClarification){const questions=clarificationQuestions(brief);if(questions.length){clearAssistantProposal();assistantClarifications=questions;renderClarificationFields($('assistant-clarification-fields'),questions);$('assistant-clarification').hidden=false;$('brief-status').textContent='Avklar noen detaljer først. Du kan også velge et foreløpig forslag med uavklarte mål.';return;}}
 clearAssistantProposal();const ticket=assistantTicket,projectId=activeProject;assistantBusy=true;$('brief-generate').disabled=true;$('wizard-ai-review').disabled=true;$('brief-status').textContent='AI vurderer oppgaver i biblioteket. Kalkylen endres ikke før du godkjenner.';
 try{const proposal=await requestEstimate(brief);if(ticket!==assistantTicket||projectId!==activeProject||brief!==$('job-brief').value.trim())return;validateProposal({summary:proposal.summary,items:proposal.items,questions:proposal.questions},library);renderAssistantProposal(proposal,brief);$('brief-status').textContent='Forslaget er klart til kontroll. Ingen oppgaver er lagt til.';}
 catch(e){if(ticket===assistantTicket&&projectId===activeProject)$('brief-status').textContent=e.message||'Kunne ikke lage AI-forslag.';}
 finally{assistantBusy=false;$('brief-generate').disabled=!assistantReady;$('wizard-ai-review').disabled=!assistantReady;}
}
$('brief-generate').onclick=()=>{assistantWizardReview=false;generateAssistant();};
$('wizard-ai-review').onclick=()=>{if(assistantBusy)return;const invalid=[...document.querySelectorAll('#questions input[type=number]')].find(e=>!e.disabled&&!e.checkValidity());if(invalid){invalid.reportValidity();$('status').textContent='Fyll inn gyldige veiviservalg før AI kontrollerer arbeidslisten.';return;}try{$('job-brief').value=wizardBrief(lastSettings,rows,$('job-brief').value);assistantWizardReview=true;generateAssistant();$('job-composer').scrollIntoView({behavior:'smooth',block:'start'});}catch(error){$('status').textContent=error.message;}};
function renderClarificationFields(container,questions){
 container.replaceChildren();for(const q of questions){const label=document.createElement('label');label.textContent=q.label;let input;
  if(q.type==='select'){input=document.createElement('select');input.add(new Option('Velg …',''));for(const value of q.options)input.add(new Option(value,value));}
  else{input=document.createElement('input');input.type=q.type||'text';input.maxLength=500;if(q.type==='number'){input.min=q.min;input.max=q.max;input.step=q.step||'any';}}
  input.dataset.clarification=q.id;label.append(input);if(q.type==='number'&&q.unit){const hint=document.createElement('small');hint.className='muted';hint.textContent='Oppgi i '+q.unit;label.append(hint);}container.append(label);
 }
}
function continueWithAnswers(questions,container){
 const answers={};for(const input of container.querySelectorAll('[data-clarification]')){if(!input.checkValidity()){input.reportValidity();return;}answers[input.dataset.clarification]=input.value;}
 try{const updated=appendClarificationAnswers($('job-brief').value.trim(),questions,answers);if(updated===$('job-brief').value.trim()){$('brief-status').textContent='Svar på minst ett spørsmål, eller velg Lag foreløpig forslag.';return;}$('job-brief').value=updated;clearAssistantProposal();generateAssistant(true);}catch(error){$('brief-status').textContent=error.message;}
}
$('assistant-clarification-form').onsubmit=event=>{event.preventDefault();continueWithAnswers(assistantClarifications,$('assistant-clarification-fields'));};
$('assistant-preliminary').onclick=()=>generateAssistant(true);
$('assistant-apply').onclick=()=>{
 const proposal=assistantProposal;if(!proposal||proposal.projectId!==activeProject||proposal.brief!==$('job-brief').value.trim()){$('brief-status').textContent='Beskrivelsen eller prosjektet er endret. Lag et nytt forslag.';return;}
 const selections=[];for(const card of $('assistant-items').children){if(!card.querySelector('[data-assistant-element]').checked)continue;const e=library.find(e=>e.id===card.dataset.elementId);const input=card.querySelector('[data-assistant-quantity]');if(!input.checkValidity()){$('brief-status').textContent='Kontroller mengdene i forslaget.';return;}const selected=[...card.querySelectorAll('[data-assistant-task]:checked')].map(t=>t.dataset.assistantTask);if(!selected.length)continue;const subset={...e,tasks:e.tasks.filter(t=>selected.includes(t.id))};selections.push({element:subset,quantity:input.value===''?0:Number(input.value)});}
 if(!selections.length){$('brief-status').textContent='Velg minst én oppgave.';return;}if(rows.length+selections.reduce((sum,s)=>sum+s.element.tasks.length,0)>500){$('brief-status').textContent='Maks 500 oppgaver i kalkylen.';return;}
 const m=proposal.measurements;if(!$('assistant-settings-label').hidden&&$('assistant-use-settings').checked&&m.roofType){job='roof';setupJob();$('roofType').value=m.roofType;if(m.area!==null)$('area').value=m.area;if(m.angle!==null)$('angle').value=m.angle;if(m.basis)$('basis').value=m.basis;configureRoof();lastSettings=settings();}
 const additions=applyTimeCatalog(selections.flatMap(s=>proposalRows(s.element,s.quantity,'-ai-'+crypto.randomUUID(),lastSettings)).map(r=>roofConsumption(r,lastSettings)),timeCatalog);
 rows.push(...additions);edited=true;renderRows();update();view(proposal.fromWizard?calculationMode==='detailed':true);$('library-browser').open=false;clearAssistantProposal();$('brief-status').textContent=additions.length+' oppgaver lagt til med bibliotekets grunntider og prosjektets timesatser. Velg markedsvarer og kontroller manglende opplysninger.';saveProject();
};
async function refreshAssistantConnection(){
 $('assistant-badge').disabled=true;$('assistant-badge').textContent='Sjekker AI-tilkobling';
 const response=await assistantStatus();const status=typeof response==='boolean'?{ready:response,state:response?'ready':'unavailable'}:response;
 assistantReady=status.ready===true;$('brief-generate').disabled=!assistantReady||assistantBusy;$('wizard-ai-review').disabled=!assistantReady||assistantBusy;
 $('assistant-badge').textContent=({'ready':'AI-assistent klar','missing-function':'AI-assistenten er ikke publisert','missing-secrets':'AI-oppsettet er ufullstendig','gateway-auth':'AI-tilkoblingen må konfigureres','unavailable':'AI-tilkoblingen kunne ikke bekreftes'})[status.state]||'AI-tilkoblingen kunne ikke bekreftes';
 $('assistant-badge').disabled=false;$('assistant-badge').title='Sjekk AI-tilkoblingen på nytt';
 $('brief-generate').title=assistantReady?'Lager et forslag som du kontrollerer før det legges til':'AI-assistenten må være tilgjengelig før forslag kan lages';
}
$('assistant-badge').onclick=refreshAssistantConnection;
refreshAssistantConnection();

refreshMarketPrices();
