import {productTypes} from './market-product-types.js';
import {priceApi} from './market-price-client.js';
import {purchaseCost} from './market-price-core.js';
const kindSelect=document.querySelector('#group-form [name=kind]');kindSelect.replaceChildren();for(const [key,type] of Object.entries(productTypes)){const option=document.createElement('option');option.value=key;option.textContent=type.name;kindSelect.append(option);}kindSelect.value='insulation';function typeHelp(){const type=productTypes[kindSelect.value];document.querySelector('#group-form [name=unit]').value=type.unit;document.querySelector('#group-spec-help').textContent='Obligatoriske spesifikasjoner: '+type.fields.join(', ')+'. Mål i mm; lambda i W/(m·K). Pakningsinnhold registreres på kildeproduktet. Ukjente verdier må avklares før godkjenning.';}kindSelect.onchange=typeHelp;typeHelp();
const $=id=>document.getElementById(id);let catalog={offers:[]},admin;
const money=ore=>new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK'}).format(ore/100);
const element=(tag,text)=>{const e=document.createElement(tag);e.textContent=text;return e;};
function showOffers(){const list=$('offers');list.replaceChildren();const quantity=Number($('purchase-quantity').value);let group='';for(const o of [...catalog.offers].sort((a,b)=>a.product.group_id.localeCompare(b.product.group_id)||a.normalized_ore-b.normalized_ore)){if(o.product.group_id!==group){group=o.product.group_id;list.append(element('h2','Sammenligningsgruppe: '+(catalog.groups?.find(g=>g.id===group)?.name||group)));}const p=o.product,card=element('article','');card.className='panel';card.append(element('h3',p.name),element('p',p.chain+' · '+(p.store_id?'Butikk '+p.store_id:'Nettpris')+' · '+JSON.stringify(p.specs)),element('p',money(o.original_ore)+' / '+p.original_unit+' ('+p.vat+' MVA) · '+money(o.normalized_ore)+'/'+p.unit+' ekskl. MVA · '+p.price_kind),element('p','Sist kontrollert: '+new Date(o.checked_at).toLocaleString('nb-NO')+' · '+(o.fresh?'Innenfor 24 timer':'Gammel pris – brukes ikke')+' · Lager: '+o.availability),element('p','Omregning: '+o.conversion),element('p',o.comparison_status==='identical'?'Identisk produkt hos annen kjede (ID og spesifikasjoner).':o.comparison_status==='equivalent'?'Alternativ med tilsvarende dokumenterte spesifikasjoner.':'Ingen bekreftet sammenligningspartner hos annen kjede.'));if(Number.isFinite(quantity)&&quantity>=0){const purchase=purchaseCost(quantity,Number(p.package_quantity),Number(o.original_ore));card.append(element('p','Behov: '+quantity+' '+p.unit+' · Kjøp: '+purchase.packages+' '+p.original_unit+' = '+purchase.purchased+' '+p.unit+' · '+money(purchase.costOre)+' '+p.vat+' MVA. Frakt er ikke kjent og er ikke inkludert.'));}const link=element('a','Se produkt hos kjeden ↗');link.href=p.url;link.rel='noopener noreferrer';link.target='_blank';card.append(link);list.append(card);}if(!catalog.offers.length)list.append(element('p','Ingen verifiserte pristilbud er registrert.'));}
async function load(){try{catalog=await priceApi('catalog');showOffers();$('price-notice').textContent='Prisregister hentet. Bare ferske, tilgjengelige og ubetingede tilbud brukes automatisk.';try{admin=await priceApi('admin');renderAdmin();$('price-admin').hidden=false;}catch{/* admin-only controls */}}catch(e){$('price-notice').textContent=e.message+' Ingen leverandørpriser er bekreftet.';}}
function renderAdmin(){const select=$('product-group');select.replaceChildren();for(const g of admin.groups){const o=element('option',g.name+' · '+g.price_key);o.value=g.id;select.append(o);}$('sources').replaceChildren();for(const source of admin.sources){const f=element('form','');f.className='panel';f.append(element('h3',source.chain));const note=document.createElement('input');note.value=source.permission_note;note.required=true;const noteLabel=element('label','Tillatelse / kontroll av vilkår og robots.txt');noteLabel.append(note);f.append(noteLabel);const hours=document.createElement('input');hours.type='number';hours.min=6;hours.max=168;hours.value=source.interval_hours;const interval=element('label','Oppdateringsintervall, timer');interval.append(hours);f.append(interval);const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=source.enabled;const en=element('label','Kilde aktiv');en.className='check';en.prepend(enabled);f.append(en);const permitted=document.createElement('input');permitted.type='checkbox';permitted.checked=source.permitted;const pe=element('label','Tillatt innhenting er dokumentert');pe.className='check';pe.prepend(permitted);f.append(pe);const next=source.last_started_at?new Date(Date.parse(source.last_started_at)+source.interval_hours*3600000).toLocaleString('nb-NO'):'Ingen kjøring ennå';f.append(element('p','Neste kildekontroll tidligst: '+next+' (køen behandles hvert kvarter etter aktivering; hver vare følger kildeintervallet).'));f.append(element('button','Lagre kilde'));f.onsubmit=async e=>{e.preventDefault();await mutate('source',{chain:source.chain,enabled:enabled.checked,permitted:permitted.checked,permission_note:note.value,interval_hours:Number(hours.value)});};$('sources').append(f);}
 $('products').replaceChildren();for(const p of admin.products){const card=element('article','');card.className='panel';card.append(element('h3',p.name),element('p',p.chain+' · '+(p.approved?'Godkjent':'Ikke godkjent')+' · '+(p.enabled?'Aktiv':'Deaktivert')),element('p','Siste forsøk: '+(p.last_attempt_at||'aldri')+' · Siste vellykkede kontroll: '+(p.last_success_at||'aldri')),element('p',p.last_error||'Ingen registrert feil'));const edit=element('button','Rediger produkt');edit.onclick=()=>{for(const [k,v] of Object.entries(p)){const field=$('product-form').elements.namedItem(k);if(!field)continue;if(field.type==='checkbox')field.checked=Boolean(v);else field.value=k==='specs'?JSON.stringify(v):v??'';}$('product-form').scrollIntoView({behavior:'smooth'});};card.append(edit);$('products').append(card);}
 $('jobs').replaceChildren();for(const job of admin.jobs)$('jobs').append(element('p',job.started_at+' · '+job.status+' · '+job.succeeded+' vellykkede / '+job.failed+' feil · '+(job.error||'')));for(const o of admin.observations.filter(o=>!o.accepted))$('jobs').append(element('p','Flagget pris '+o.product_id+': '+o.flag+' · '+money(o.normalized_ore)+'/'+o.unit+' – holdes utenfor kalkylen. Verifiser kilden og kjør på nytt etter korrigering.'));
}
async function mutate(action,body){try{await priceApi(action,body);$('price-notice').textContent='Lagret.';admin=await priceApi('admin');renderAdmin();}catch(e){$('price-notice').textContent=e.message;}}
$('group-form').onsubmit=e=>{e.preventDefault();try{const group=Object.fromEntries(new FormData(e.target));group.specs=JSON.parse(group.specs);mutate('group',{group});}catch{$('price-notice').textContent='Spesifikasjoner må være gyldig JSON.';}};
$('product-form').onsubmit=e=>{e.preventDefault();try{const product=Object.fromEntries(new FormData(e.target));product.package_quantity=Number(product.package_quantity);product.specs=JSON.parse(product.specs);product.enabled=e.target.elements.enabled.checked;product.approved=e.target.elements.approved.checked;mutate('product',{product});}catch{$('price-notice').textContent='Spesifikasjoner må være gyldig JSON.';}};
$('sync').onclick=async()=>{$('sync').disabled=true;$('sync-status').textContent='Kontrollerer kildene på serveren …';try{const job=await priceApi('sync');$('sync-status').textContent=job.status==='already_running_or_recent'?'En jobb kjører allerede eller ble nylig startet.':job.succeeded+' kontrollerte priser; '+job.failed+' feil.';await load();}catch(e){$('sync-status').textContent=e.message;}finally{$('sync').disabled=false;}};
$('reload').onclick=load;$('purchase-quantity').oninput=showOffers;load();
