import {test} from 'node:test';import assert from 'node:assert/strict';
import {handleEstimate} from '../supabase/functions/rigor-ai-estimate/handler.ts';import {catalog} from '../supabase/functions/rigor-ai-estimate/catalog.js';import {library} from '../kalkyle-library.js';import {shortlist,extractMeasurements,validateProposal} from '../supabase/functions/rigor-ai-estimate/proposal.js';import {proposalRows} from '../kalkyle-assistant.js';
const env={SUPABASE_URL:'https://test.supabase.co',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service',RIGOR_OPENAI_KEY:'fixture-key'};
const brief='Saltak, 30 grader og 100 m² takflate. Ta med takstein, sløfyer, sutak og vannrenner.';
const proposal={summary:'Testforslag',items:[{elementId:'roof.underlay',taskIds:['underlay','battens','laths'],scope:'requested',reason:'Undertak, sløyfer og lekter'}],questions:['Hva er samlet lengde på takrennene?']};
function request(body={brief},token=true){return new Request('https://example.test',{method:'POST',headers:{Origin:'https://rigor.no','Content-Type':'application/json',...(token?{Authorization:'Bearer fixture-token'}:{})},body:JSON.stringify(body)});}
function setup(options={}){let calls=0,payload,logged;return {env:k=>options.noKey&&k==='RIGOR_OPENAI_KEY'?undefined:env[k],fetch:async(url,init)=>{if(url.endsWith('/auth/v1/user'))return options.badAuth?Response.json({},{status:401}):Response.json({id:'fixture-user'});if(url.endsWith('/rpc/portal_has_access'))return Response.json(!options.inactive);if(url.endsWith('/rpc/portal_is_admin'))return Response.json(!options.member);if(url.includes('portal_tool_access'))return Response.json(options.allowed?[{tool_key:'kalkyle'}]:[]);if(url.endsWith('/rpc/reserve_rigor_ai_estimate'))return options.quota?Response.json({},{status:400}):Response.json('reservation');if(url==='https://api.openai.com/v1/chat/completions'){calls++;payload=JSON.parse(init.body);return options.apiError?Response.json({},{status:429}):Response.json({choices:[{message:{content:JSON.stringify(options.proposal||proposal)}}],usage:{prompt_tokens:5000,completion_tokens:250}});}if(url.includes('/rigor_ai_estimate_usage?')){logged=JSON.parse(init.body);return options.logError?Response.json({},{status:500}):new Response(null,{status:204});}throw Error('Unexpected fixture URL '+url);},calls:()=>calls,payload:()=>payload,logged:()=>logged};}
test('Ingen AI-kall uten innlogging, secret og aktiv portalkonto',async()=>{for(const options of [{noKey:true},{badAuth:true},{inactive:true}]){const deps=setup(options);assert.notEqual((await handleEstimate(request(),deps)).status,200);assert.equal(deps.calls(),0);}const deps=setup();assert.equal((await handleEstimate(request({brief},false),deps)).status,401);});
test('Medlem må ha tildelt kalkyleverktøy',async()=>{let deps=setup({member:true});assert.equal((await handleEstimate(request(),deps)).status,403);assert.equal(deps.calls(),0);deps=setup({member:true,allowed:true});assert.equal((await handleEstimate(request(),deps)).status,200);});
test('Forbruksgrense og stor input stopper før fakturering',async()=>{const deps=setup({quota:true});assert.equal((await handleEstimate(request(),deps)).status,429);assert.equal(deps.calls(),0);const large=setup();assert.equal((await handleEstimate(request({brief:'x'.repeat(20000)}),large)).status,413);assert.equal(large.calls(),0);});
test('Forslag bruker serverbibliotek, begrenset output og lagrer kun tokenantall',async()=>{const deps=setup();const r=await handleEstimate(request(),deps);assert.equal(r.status,200);const result=await r.json();assert.equal(result.measurements.area,100);assert.equal(result.measurements.angle,30);assert.equal(result.measurements.roofType,'gable');assert.equal(deps.payload().max_completion_tokens,3000);assert(deps.payload().response_format.json_schema.strict);assert.equal(deps.payload().model,'gpt-4.1-mini');assert.deepEqual(deps.logged(),{input_tokens:5000,output_tokens:250});});
test('Ukjente ID-er, prisfelt og dupliserte oppgaver avvises',async()=>{for(const output of [{...proposal,items:[{...proposal.items[0],elementId:'unknown'}]},{...proposal,price:999},{...proposal,items:[{...proposal.items[0],taskIds:['battens','battens']}]}]){const deps=setup({proposal:output});assert.equal((await handleEstimate(request(),deps)).status,502);}});
test('API-feil og feil i forbrukslogging bekreftes ikke som forslag',async()=>{for(const options of [{apiError:true},{logError:true}])assert.notEqual((await handleEstimate(request(),setup(options))).status,200);});
test('Helsetest bruker ingen AI-kall og viser bare tilkoblingsstatus',async()=>{const deps=setup();const r=await handleEstimate(new Request('https://test',{method:'GET'}),deps);assert.deepEqual(await r.json(),{ready:true});assert.equal(deps.calls(),0);});
test('Autoritativt katalogsnapshot samsvarer med standardbiblioteket',()=>{assert.deepEqual(catalog.map(e=>[e.id,e.tasks.map(t=>t.id)]),library.map(e=>[e.id,e.tasks.map(t=>t.id)]));assert(shortlist(brief,catalog).some(e=>e.id==='roof.underlay'));});
test('Mål leses bare fra entydige opplysninger; lengder og arbeidstid gjettes ikke',()=>{assert.equal(extractMeasurements('100 m² takflate og 50 m² vegg').area,null);assert.equal(extractMeasurements('100 m2').basis,null);assert.equal(extractMeasurements('Et nytt tak').angle,null);const e=library.find(e=>e.id==='roof.ridge');const rows=proposalRows(e,0,'-fixture');assert(rows.every(r=>r.requiresQuantity&&r.requiresTime&&r.hours===0));assert.throws(()=>validateProposal({...proposal,items:[{...proposal.items[0],taskIds:['invented']}]},catalog));});
