import {readFileSync} from 'node:fs';
import {validatePrices,applyPrices} from '../kalkyle-prices.js';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {publicSources,sourceUrl,retailerTaxEvidence,readPublicProducts,robotsPolicy,sitemapLinks,readPublicProduct,usableOffer,selectedPrices,offersForRow,materialPriority,normalizePublicOffer} from '../market-public-core.js';
import {syncPublicPrices} from '../scripts/sync-public-prices.mjs';
import {readByggmaxPage,byggmaxPriceUrl,readByggmaxPrices} from '../market-byggmax-core.js';
const source=publicSources[0],url=source.origin+'/trelast/sloyfer/1234567',now='2026-10-06T12:00:00.000Z';
const product={'@type':'Product',sku:'fixture',name:'Sløyfe 23x48 gran',url,offers:{'@type':'Offer',url,price:'25',priceCurrency:'NOK',availability:'https://schema.org/InStock',priceSpecification:{'@type':'UnitPriceSpecification',price:'25',priceCurrency:'NOK',valueAddedTaxIncluded:true,referenceQuantity:{value:1,unitCode:'MTR'}}}};
const html=(p=product,extra='')=>'<script type="application/ld+json">'+JSON.stringify(p)+'</script>'+extra;
test('Eksakt leverandøradresse, sitemaps og bread-and-butter-prioritet',()=>{assert.throws(()=>sourceUrl('https://www.obsbygg.no.evil.test/a',source));assert.throws(()=>sourceUrl('http://www.obsbygg.no/a',source));assert.deepEqual(sitemapLinks('<urlset><url><loc>https://www.obsbygg.no/a?x=1&amp;y=2</loc></url></urlset>').urls,['https://www.obsbygg.no/a?x=1&y=2']);assert(materialPriority('/sloyfer-23x48')>0);});
test('Robots bruker spesifikk agent, lengste regel, Allow ved likhet og query',()=>{const p=robotsPolicy('User-agent: *\nDisallow: /\nUser-agent: RIGOR\nDisallow: /private\nAllow: /private/public\nDisallow: /*?store=\nCrawl-delay: 4');assert(p.allows(source.origin+'/trelast'));assert(!p.allows(source.origin+'/private/a'));assert(p.allows(source.origin+'/private/public/a'));assert(!p.allows(source.origin+'/a?store=42'));assert.equal(p.delay,4);});
test('NOK, MVA, referansemengde, lager og produkt-ID leses fra kilden',()=>{const o=readPublicProduct(html(),url,source,now);assert.equal(o.normalized_ore,2000);assert.equal(o.package_quantity,1);assert.equal(o.kind,'battens');assert.equal(o.source_id,'fixture');assert(usableOffer(o,Date.parse(now)));const ps={...product.offers.priceSpecification,referenceQuantity:{value:4.8,unitCode:'MTR'}};assert.equal(readPublicProduct(html({...product,offers:{...product.offers,priceSpecification:ps}}),url,source,now).normalized_ore,417);});
test('Synlig pris/enhet krever samme prisverdi og entydig MVA; m² fungerer',()=>{const p={...product,name:'Isolasjon 100 mm',offers:{...product.offers,price:600,priceSpecification:undefined}};assert.equal(readPublicProduct(html(p,'<p>600,00 kr/m² inkl. mva</p>'),url,source,now).unit,'m2');assert.throws(()=>readPublicProduct(html(p,'<p>599,00 kr/m² inkl. mva</p>'),url,source,now));assert.throws(()=>readPublicProduct(html(p,'<p>600 kr/m²</p>'),url,source,now));assert.throws(()=>readPublicProduct(html(p,'<p>Medlemspris 600 kr/m² inkl. mva</p>'),url,source,now));});
test('Ukjent/lokal/fra-pris/produktliste eller utløpt pris kan ikke brukes',()=>{for(const patch of [{priceCurrency:'EUR'},{availableAtOrFrom:'local'},{eligibleCustomerType:'member'},{availability:'unknown'},{priceValidUntil:'2026-10-05'},{'@type':'AggregateOffer'}])assert.throws(()=>readPublicProduct(html({...product,offers:{...product.offers,...patch}}),url,source,now));assert.throws(()=>readPublicProduct(html([product,product]),url,source,now));const o=readPublicProduct(html(),url,source,now);assert(!usableOffer({...o,last_error:'HTTP 403'},Date.parse(now)));assert(!usableOffer(o,Date.parse(now)+25*3600000));});
test('Priser brukes først ved eksplisitt produktvalg og riktig materialtype/enhet',()=>{const o=readPublicProduct(html(),url,source,now),r={priceKey:'roof.underlay.sloyfer',materialUnit:'m',name:'Montere sløyfer'};assert.equal(selectedPrices([o],{},Date.parse(now)).length,0);assert.equal(selectedPrices([o],{[r.priceKey]:o.id},Date.parse(now))[0].pris,20);assert.equal(offersForRow(r,[o],Date.parse(now)).length,1);assert.equal(offersForRow({...r,materialUnit:'m²'},[o],Date.parse(now)).length,0);});
test('Takstein, metalltekking og undertak kan ikke prises med en annen varetype',()=>{
 const base=readPublicProduct(html(),url,source,now);
 const offers=[{...base,id:'tile',name:'Betong takstein',kind:'roofing',unit:'m2'},{...base,id:'metal',name:'Takplate stål',kind:'roofing',unit:'m2'},{...base,id:'shingle',name:'Takshingel',kind:'roofing',unit:'m2'},{...base,id:'underlay',name:'Diffusjonsåpent undertak',kind:'membranes',unit:'m2'},{...base,id:'barrier',name:'Vindsperre',kind:'membranes',unit:'m2'}];
 for(const [key,name,id] of [['roof.cover.tile','Legge takstein','tile'],['roof.cover.metal','Montere metalltekking','metal'],['roof.underlay.undertak','Legge undertak','underlay']])assert.deepEqual(offersForRow({priceKey:key,name,materialUnit:'m²'},offers,Date.parse(now)).map(o=>o.id),[id]);
});
function fixtureFetch(fail=false,price=25){const calls=[];const fn=async(u,opts)=>{calls.push(u);assert.equal(opts.redirect,'error');if(u===source.vat_policy_url)return new Response('Alle priser er inkludert merverdiavgift.');if(u.endsWith('/robots.txt'))return new Response('User-agent: *\nAllow: /\nSitemap: '+source.origin+'/sitemap.xml');if(u===source.origin+'/sitemap.xml')return new Response('<urlset><url><loc>'+url+'</loc></url><url><loc>https://evil.test/isolasjon</loc></url></urlset>');if(u===url)return fail?new Response('blocked',{status:403}):new Response(html({...product,offers:{...product.offers,price,priceSpecification:{...product.offers.priceSpecification,price}}}));return new Response('blocked',{status:403});};return {fn,calls};}
test('Innhentingsjobb oppdager produkter, bruker ikke AI og stopper ved kildeblokkering',async()=>{const f=fixtureFetch(),r=await syncPublicPrices({fetcher:f.fn,clock:()=>Date.parse(now),pause:async()=>{},maxProducts:2});assert.equal(r.catalog.offers.length,1);assert.equal(r.catalog.last_run.succeeded,1);assert(r.queue.urls.every(q=>q.url.startsWith(source.origin)));assert(!f.calls.some(u=>u.includes('openai')));});
test('Feil bevarer forrige pris og kontrolltid, men sperrer prisen; store hopp flagges',async()=>{const o=readPublicProduct(html(),url,source,now);for(const f of [fixtureFetch(true),fixtureFetch(false,100)]){const r=await syncPublicPrices({previous:{offers:[o]},queue:{urls:[{url,chain:'obs',priority:90}],last_discovery:{obs:now}},fetcher:f.fn,clock:()=>Date.parse(now)+1000,pause:async()=>{},maxProducts:2});assert.equal(r.catalog.offers[0].normalized_ore,o.normalized_ore);assert.equal(r.catalog.offers[0].checked_at,now);assert(r.catalog.offers[0].last_error);assert.equal(r.catalog.last_run.failed,1);}});
test('Oppdagelse fortsetter neste sitemap ved puljegrensen',async()=>{const maps=[source.origin+'/a.xml',source.origin+'/b.xml'];const fetcher=async u=>new Response(u===source.vat_policy_url?'Alle priser er inkludert merverdiavgift.':u.endsWith('robots.txt')?'Sitemap: '+maps[0]+'\nSitemap: '+maps[1]:'<urlset></urlset>');const first=await syncPublicPrices({fetcher,clock:()=>Date.parse(now),pause:async()=>{},maxSitemaps:1,maxProducts:0});assert.deepEqual(first.queue.last_discovery.obs.pending,[maps[1]]);const second=await syncPublicPrices({queue:first.queue,fetcher,clock:()=>Date.parse(now),pause:async()=>{},maxSitemaps:1,maxProducts:0});assert.deepEqual(second.queue.last_discovery.obs.pending,[]);});

test('Isolasjonstykkelse som er oppgitt i posten kan ikke byttes til en annen',()=>{const o=readPublicProduct(html({...product,name:'Isolasjon 100 mm',offers:{...product.offers,priceSpecification:{...product.offers.priceSpecification,referenceQuantity:{value:1,unitCode:'MTK'}}}}),url,source,now);assert.equal(offersForRow({priceKey:'insulation.isolasjon100',name:'Montere 100 mm isolasjon',materialUnit:'m²'},[o,{...o,id:'150',name:'Isolasjon 150 mm'}],Date.parse(now)).length,1);});

test('Vanlige schema-URI-er og WebPage.mainEntity støttes uten å bruke relaterte produkter',()=>{const p={...product,'@type':'https://schema.org/Product',offers:{...product.offers,'@type':'https://schema.org/Offer'}};assert.equal(readPublicProduct(html({'@type':'WebPage',mainEntity:p}).replace('type=','type = '),url,source,now).normalized_ore,2000);});

test('Dokumenterte varer blir kontrollert før ukjente adresser når budsjettet er lite',async()=>{const o=readPublicProduct(html(),url,source,now),f=fixtureFetch();const r=await syncPublicPrices({previous:{offers:[o]},queue:{urls:[{url:source.origin+'/isolasjon/isolasjon-ukjent/2345678',chain:'obs',priority:100},{url,chain:'obs',priority:95,last_attempt_at:'2026-10-05T00:00:00Z'}],last_discovery:{obs:now}},fetcher:f.fn,clock:()=>Date.parse(now)+1000,pause:async()=>{},maxProducts:2});assert.equal(r.catalog.last_run.succeeded,1);assert(!f.calls.includes(source.origin+'/isolasjon/isolasjon-ukjent/2345678'));});

test('Prisreferanse behandles ikke som fysisk pakningsinnhold eller hele bord',t=>{t.mock.timers.enable({apis:['Date'],now:Date.parse(now)});const o=readPublicProduct(html(),url,source,now),prices=validatePrices(selectedPrices([o],{test:o.id}));const row={priceKey:'test',materialUnit:'m',materialQuantity:4.2,quantity:4.2};const r=applyPrices([row],'market',prices,now.slice(0,10))[0];assert.equal(r.marketMaterialCost,undefined);assert.equal(r.marketPackages,undefined);assert.equal(r.material,20);assert(r.priceSource.includes('pakningsavrunding'));});

test('Obs ProductGroup bindes til én variant eller en eksplisitt valgt variant-URL',()=>{const variant={...product,url:url+'?v=fixture',offers:{...product.offers,url:url+'?v=fixture'}};const group={'@type':'ProductGroup',url,hasVariant:[variant]};assert.equal(readPublicProduct(html(group),url,source,now).url,variant.url);const other={...variant,sku:'other',url:url+'?v=other',offers:{...variant.offers,url:url+'?v=other'}};assert.throws(()=>readPublicProduct(html({...group,hasVariant:[variant,other]}),url,source,now));assert.equal(readPublicProduct(html({...group,hasVariant:[variant,other]}),variant.url,source,now).source_id,'fixture');});

test('Obs-variant med dokumentert pakningsareal og verifisert avgiftsvilkår får riktig pris per m²',()=>{const tax=retailerTaxEvidence('Alle priser er inkludert merverdiavgift.',source.vat_policy_url,source,now);const variant={...product,name:'Trefiberisolasjon',size:'100 MM',url:url+'?v=fixture',offers:{...product.offers,url:url+'?v=fixture',price:489,priceSpecification:undefined}};const group={'@type':'ProductGroup',url,hasVariant:[variant]};const offer=readPublicProducts(html(group,'100 mm, leveres i pakker á 2,8 m²'),url,{...source,tax_evidence:tax},now)[0];assert.equal(offer.normalized_ore,13971);assert.equal(offer.package_quantity,2.8);assert.equal(offer.quantity_basis,'package');assert.equal(offer.original_unit,'pakke');assert.throws(()=>readPublicProducts(html(group,'100 mm, leveres i pakker á 2,8 m²'),url,source,now));});


test('Nye byggevarer prioriteres foran gamle verktøyadresser og lavere materialprioritet',async()=>{
 const insulationUrl=source.origin+'/byggevarer/isolasjon/2113834';
 const p={...product,name:'Isolasjon 100 mm',url:insulationUrl,offers:{...product.offers,url:insulationUrl,priceSpecification:{...product.offers.priceSpecification,referenceQuantity:{value:1,unitCode:'MTK'}}}};
 const calls=[],fetcher=async u=>{calls.push(u);if(u===source.vat_policy_url)return new Response('Alle priser er inkludert merverdiavgift.');if(u.endsWith('/robots.txt'))return new Response('User-agent: *\nAllow: /');if(u===insulationUrl)return new Response(html(p));return new Response('blocked',{status:403});};
 const queue={parser_version:4,urls:[{url:source.origin+'/verktoy/elektroverktoy/1234567',chain:'obs',priority:95},{url:source.origin+'/gulv/parkett/2345678',chain:'obs',priority:35},{url:insulationUrl,chain:'obs',priority:100,last_attempt_at:'2026-10-05T00:00:00Z'}],last_discovery:{obs:{finished_at:now},byggmax:{finished_at:now}}};
 const r=await syncPublicPrices({queue,fetcher,clock:()=>Date.parse(now),pause:async()=>{},maxProducts:2});
 assert.equal(r.catalog.offers.length,1);assert.equal(r.catalog.offers[0].kind,'insulation');assert(!calls.some(u=>u.includes('elektroverktoy')||u.includes('parkett')));
});


const recorded=JSON.parse(readFileSync(new URL('./fixtures/obs-public-evidence-20261006.json',import.meta.url)));
const recordedSource={...source,tax_evidence:retailerTaxEvidence('Alle priser er inkludert merverdiavgift.',source.vat_policy_url,source,recorded.checked_at)};
const rolls=JSON.parse(readFileSync(new URL('./fixtures/obs-undertak-evidence-20261007.json',import.meta.url)));
function rollHtml(s){return html(s.product,'<div data-test-id="product-price-section"><div aria-description="'+s.price_aria+'"></div></div>');}
function rollOffer(index=1){const s=rolls.samples[index];return readPublicProducts(rollHtml(s),s.url,recordedSource,s.checked_at)[0];}
function legacyRoll(o=rollOffer()){return {...o,unit:'stk',original_unit:'stk',quantity_basis:'unit',package_quantity:1,normalized_ore:o.package_price_ex_vat_ore,package_area_basis:undefined,source_price_unit:undefined};}
test('Faktiske undertaksruller får m²-pris fra samme SKU og hele ruller i innkjøpet',t=>{
 const film=rollOffer(0),basic=rollOffer();
 // Historical supplier evidence must use its observation time throughout
 // selection and calculation. The live 24-hour expiry rule stays unchanged.
 t.mock.timers.enable({apis:['Date'],now:Date.parse(basic.checked_at)});
 assert.equal(film.package_quantity,32.5);assert.equal(film.normalized_ore,7924);assert.equal(film.package_price_ex_vat_ore,257520);
 assert.equal(basic.package_quantity,75);assert.equal(basic.normalized_ore,7045);assert.equal(basic.package_price_ex_vat_ore,528400);
 for(const o of [film,basic]){assert.equal(o.unit,'m2');assert.equal(o.original_unit,'rull');assert.equal(o.package_area_basis,'gross');assert.equal(o.quantity_basis,'package');assert(o.evidence.includes('brutto'));}
 const row={name:'Legge undertak',priceKey:'roof.underlay.undertak',materialUnit:'m²',quantity:115.47,materialQuantity:115.47};
 const at=Date.parse(basic.checked_at),store={byggmax:'2327'};
 assert.deepEqual(offersForRow(row,[basic,film],at,store).map(o=>o.id),[basic.id,film.id]);
 const prices=validatePrices(selectedPrices([basic],{[row.priceKey]:basic.id},at,store));
 const priced=applyPrices([row],'market',prices,basic.checked_at.slice(0,10))[0];
 assert.equal(priced.material,70.45);assert.equal(priced.marketPackages,2);assert.equal(priced.marketPurchasedQuantity,150);assert.equal(priced.marketMaterialCost,10568);
 t.mock.timers.tick(86400001);
 const expired=applyPrices([row],'market',prices)[0];
 assert.equal(expired.priceIssue,'utdatert');assert.equal(expired.material,0);assert.equal(expired.marketMaterialCost,undefined);
 assert.deepEqual(selectedPrices([basic],{[row.priceKey]:basic.id},Date.now(),store),[]);
});
test('Enhetsretting beholder kildekontroll, feil og foreldelse og avviser tvetydige rullmål',()=>{
 const raw=legacyRoll(),fixed=normalizePublicOffer(raw);
 assert.equal(fixed.checked_at,raw.checked_at);assert.deepEqual(normalizePublicOffer(fixed),fixed);assert.equal(raw.unit,'stk');
 const failed=normalizePublicOffer({...raw,last_error:'HTTP 403'});assert.equal(failed.last_error,'HTTP 403');assert(!usableOffer(failed,Date.parse(raw.checked_at)));
 assert(!usableOffer(fixed,Date.parse(raw.checked_at)+25*3600000));
 for(const patch of [{name:'Undertak 2 ruller 1,50x50 m'},{name:'Undertak 1,50x50 mm'},{name:'Undertak 1,50x50 m eller 1,30x25 m'},{name:'Undertak',shipping_dimensions:'1,50x50 m'},{kind:'roofing'},{chain:'byggmax'},{quantity_basis:'package'}]){const o={...raw,...patch};assert.equal(normalizePublicOffer(o),o);}
});
test('Prissynk kontrollerer ruller tidlig, migrerer enhetshistorikk og flagger reelle prishopp',async()=>{
 const sample=rolls.samples[1],raw=legacyRoll(),otherUrl=source.origin+'/isolasjon/isolasjon-ukjent/2345678';
 for(const multiplier of [1,2]){
  const calls=[],fetcher=async u=>{calls.push(u);if(u===source.vat_policy_url)return new Response('Alle priser er inkludert merverdiavgift.');if(u.endsWith('/robots.txt'))return new Response('User-agent: *\nAllow: /');if(u===sample.url){const s=structuredClone(sample);s.product.hasVariant[0].offers.price=String(6605*multiplier);s.price_aria=s.price_aria.replace('6605 kroner',String(6605*multiplier)+' kroner');return new Response(rollHtml(s));}return new Response('blocked',{status:403});};
  const previous={offers:[raw],price_history:[{product_id:raw.id,unit:'stk',package_quantity:1,original_ore:raw.original_ore,normalized_ore:raw.normalized_ore}]};
  const r=await syncPublicPrices({previous,queue:{parser_version:8,urls:[{url:otherUrl,chain:'obs',priority:100},{url:sample.url,chain:'obs',priority:65,next_attempt_at:'2026-10-08T00:00:00Z'}],last_discovery:{obs:rolls.checked_at,byggmax:rolls.checked_at}},fetcher,clock:()=>Date.parse(rolls.checked_at)+1000,pause:async()=>{},maxProducts:2});
  assert(!calls.includes(otherUrl));assert.equal(r.catalog.offers[0].unit,'m2');assert.equal(r.catalog.offers[0].normalized_ore,7045);
  if(multiplier===1){assert.equal(r.catalog.last_run.succeeded,1);assert.equal(r.catalog.price_history.length,2);assert.equal(r.catalog.price_history[1].unit,'m2');assert(r.catalog.offers[0].checked_at>raw.checked_at);}
  else{assert.equal(r.catalog.last_run.failed,1);assert.match(r.catalog.offers[0].last_error,/50 %/);assert.equal(r.catalog.offers[0].checked_at,raw.checked_at);assert.equal(r.catalog.price_history.length,1);}
 }
});
function recordedHtml(s){return s.ld_json.map(v=>'<script type="application/ld+json">'+v+'</script>').join('')+(s.price_markup||[]).join('')+'<p>'+s.visible+'</p>';}
test('Faktisk Obs-markup for 11x36 lekt gir 10,80 kr per løpemeter ekskl. MVA',()=>{const s=recorded.samples.find(s=>s.url.includes('2100592'));const o=readPublicProducts(recordedHtml(s),s.url,recordedSource,recorded.checked_at)[0];assert.equal(o.normalized_ore,1080);assert.equal(o.unit,'m');assert.equal(o.kind,'battens');assert.equal(o.quantity_basis,'unit');const mismatched=recordedHtml(s).replace('13 kroner','14 kroner');assert.throws(()=>readPublicProducts(mismatched,s.url,recordedSource,recorded.checked_at));});
test('Faktisk gipsplate omregnes fra stykk til m² med dokumenterte platedimensjoner',()=>{const s=recorded.samples.find(s=>s.url.includes('2126273'));const o=readPublicProducts(recordedHtml(s),s.url,recordedSource,recorded.checked_at)[0];assert.equal(o.unit,'m2');assert.equal(o.package_quantity,3.12);assert.equal(o.original_unit,'plate');assert.equal(o.normalized_ore,16026);assert.equal(o.quantity_basis,'package');});
test('Fire dokumenterte Hunton-varianter brukes; 70 mm uten pakningsareal holdes ute',()=>{const s=recorded.samples.find(s=>s.url.includes('2113834')),rejected=[];const o=readPublicProducts(recordedHtml(s),s.url,recordedSource,recorded.checked_at,e=>rejected.push(e));assert.equal(o.length,4);assert.equal(rejected.length,1);assert(rejected[0].error.includes('Prisenhet'));assert.equal(o.find(o=>o.name.includes('100 MM')).normalized_ore,13971);});
test('Et priset stykk med 100-pk i navnet kan ikke regnes som én skrue eller plugg',()=>{const p={...product,name:'Fischer isolasjonsplugg 100-pk',offers:{...product.offers,priceSpecification:{...product.offers.priceSpecification,referenceQuantity:{value:1,unitCode:'C62'}}}};const offer=readPublicProduct(html(p),url,source,now);assert.equal(offer.package_quantity,100);assert.equal(offer.quantity_basis,'package');assert.equal(offer.normalized_ore,Math.round(offer.package_price_ex_vat_ore/100));assert(usableOffer(offer,Date.parse(now)));});
test('Andre kontroll av samme kildeprodukt gir ingen dupliserte produkter eller uendrede historikkpriser',async()=>{const first=await syncPublicPrices({fetcher:fixtureFetch().fn,clock:()=>Date.parse(now),pause:async()=>{},maxProducts:2});const second=await syncPublicPrices({previous:first.catalog,queue:first.queue,fetcher:fixtureFetch().fn,clock:()=>Date.parse(now)+21600001,pause:async()=>{},maxProducts:2});assert.equal(second.catalog.offers.length,1);assert.equal(second.catalog.price_history.length,1);assert.equal(second.catalog.job_history.length,2);assert.equal(second.catalog.last_run.succeeded,1);assert(second.catalog.offers[0].checked_at>first.catalog.offers[0].checked_at);});


test('Maling for vindu/dør kan ikke bli et vindu, og isolasjonspakke uten areal er ikke en m²-pris',()=>{const p={...product,name:'Jotun Drygolin Vindu og Dør',offers:{...product.offers,priceSpecification:{...product.offers.priceSpecification,referenceQuantity:{value:1,unitCode:'C62'}}}};assert.throws(()=>readPublicProduct(html(p),url,source,now),/støttet byggevare/);assert(!usableOffer({...readPublicProduct(html(),url,source,now),kind:'windows',name:p.name},Date.parse(now)));const iso={...p,name:'Trefiberisolasjon 70 mm'};assert.throws(()=>readPublicProduct(html(iso),url,source,now),/Pakningsareal/);});

const bm=JSON.parse(readFileSync(new URL('./fixtures/byggmax-public-evidence-20261006.json',import.meta.url))),bmSource=publicSources[1],bmTax=retailerTaxEvidence(bm.tax,bmSource.vat_policy_url,bmSource,bm.checked_at);
function bmOffers(sample=0,store='2327'){const s=bm.samples[sample];return readByggmaxPrices(readByggmaxPage(s.html,s.url),s.csp.find(c=>c.store_id===store).data,store,bmTax,bm.checked_at);}
test('Faktiske Byggmax-priser for samme lekt holdes atskilt per butikk, uten nasjonal minstepris',()=>{const grimstad=bmOffers()[0],arendal=bmOffers(0,'2314')[0];assert.equal(grimstad.normalized_ore,1268);assert.equal(arendal.normalized_ore,1176);assert.equal(grimstad.store_name,'Grimstad');assert.notEqual(grimstad.id,arendal.id);assert.equal(bmOffers(0,'0').length,0);const at=Date.parse(bm.checked_at);assert.equal(selectedPrices([grimstad,arendal],{lekt:grimstad.id},at).length,0);assert.equal(selectedPrices([grimstad,arendal],{lekt:grimstad.id},at,{byggmax:'2314'}).length,0);assert.equal(selectedPrices([grimstad,arendal],{lekt:grimstad.id},at,{byggmax:'2327'})[0].pris,12.68);assert.equal(offersForRow({priceKey:'roof.sloyfer',materialUnit:'m',name:'Sløyfer'},[grimstad,arendal],at,{byggmax:'2314'})[0].id,arendal.id);});
test('Byggmax gips 12,5×1200×2500 mm kjøpes som hele plater, ikke løs m²',t=>{
 t.mock.timers.enable({apis:['Date'],now:Date.parse(bm.checked_at)});
 const o=bmOffers(3)[0];assert.equal(o.original_ore,19900);assert.equal(o.package_price_ex_vat_ore,15920);assert.equal(o.package_quantity,3);assert.equal(o.normalized_ore,5307);
 const prices=validatePrices(selectedPrices([o],{gips:o.id},Date.now(),{byggmax:'2327'}));
 const row={priceKey:'gips',materialUnit:'m²',materialQuantity:4,quantity:4};
 const rows=applyPrices([row],'market',prices,bm.checked_at.slice(0,10));assert.equal(rows[0].marketPackages,2);assert.equal(rows[0].marketMaterialCost,318.4);
 t.mock.timers.tick(86400001);
 const expired=applyPrices([row],'market',prices)[0];assert.equal(expired.priceIssue,'utdatert');assert.equal(expired.marketPackages,undefined);
});
test('Faktisk Byggmax-isolasjon bruker dokumentert 6,20 m² pakke og 557,70 kr pakkepris; ukjente eller motstridende data sperres',t=>{
 t.mock.timers.enable({apis:['Date'],now:Date.parse(bm.checked_at)});
 const s=bm.samples[2],page=readByggmaxPage(s.html,s.url),data=s.csp.find(c=>c.store_id==='2314').data,o=bmOffers(2,'2314')[0];assert.equal(o.package_quantity,6.2);assert.equal(o.original_ore,55770);assert.equal(o.normalized_ore,7196);assert.equal(o.original_unit,'pakke');assert(o.name.includes('565x1220x50'));assert.equal(offersForRow({priceKey:'insulation.isolasjon100',name:'Montere 100 mm isolasjon',materialUnit:'m²'},[o],Date.now(),{byggmax:'2314'}).length,0);
 const prices=validatePrices(selectedPrices([o],{iso:o.id},Date.now(),{byggmax:'2314'})),row={priceKey:'iso',materialUnit:'m²',materialQuantity:6.3,quantity:6.3};
 assert.equal(applyPrices([row],'market',prices,bm.checked_at.slice(0,10))[0].marketMaterialCost,892.32);
 const bad=structuredClone(page);Object.values(bad.optionData)[0].package_size='5,00';assert.equal(readByggmaxPrices(bad,data,'2314',bmTax,bm.checked_at).length,0);assert.equal(readByggmaxPrices({...page,packagePriceCode:false},data,'2314',bmTax,bm.checked_at).length,0);const wrong=structuredClone(data);Object.values(wrong.articles)[0].bmx_base_price=500;assert.equal(readByggmaxPrices(page,wrong,'2314',bmTax,bm.checked_at).length,0);
 t.mock.timers.tick(86400001);
 const expired=applyPrices([row],'market',prices)[0];assert.equal(expired.priceIssue,'utdatert');assert.equal(expired.marketMaterialCost,undefined);
});
test('Byggmax svar med feil butikk/vare, skjult vare, tomt lager eller ukjent MVA brukes ikke',()=>{const s=bm.samples[0],page=readByggmaxPage(s.html,s.url),data=s.csp.find(c=>c.store_id==='2327').data;assert.throws(()=>readByggmaxPrices(page,{...data,selected_shop:2314},'2327',bmTax,bm.checked_at));assert.throws(()=>readByggmaxPrices(page,{...data,sku:'P-other'},'2327',bmTax,bm.checked_at));assert.throws(()=>readByggmaxPrices(page,data,'2327',null,bm.checked_at));assert.throws(()=>byggmaxPriceUrl(page,'99999'));for(const patch of [{qty:0},{is_salable:false},{discontinued:true}]){const changed=structuredClone(data);Object.assign(Object.values(changed.articles)[0],patch);assert.equal(readByggmaxPrices(page,changed,'2327',bmTax,bm.checked_at).length,0);}assert.equal(bmOffers(2).length,0);assert.equal(bmOffers(2,'2314').length,1);});
function bmFetcher(failStore=false){return async u=>{if(new URL(u).origin!==bmSource.origin)return new Response('unavailable',{status:403});if(u.endsWith('/robots.txt'))return new Response('User-agent: *\nDisallow: /catalog/');if(u===bmSource.vat_policy_url)return new Response(bm.tax);const s=bm.samples.find(s=>s.url===u);if(s)return new Response(s.html);const endpoint=new URL(u);if(endpoint.pathname==='/gcsp'){assert.equal(endpoint.searchParams.get('customerType'),'0');const sample=bm.samples.find(s=>s.csp.some(c=>c.url===u));const c=sample?.csp.find(c=>c.url===u);if(c)return failStore&&c.store_id==='2327'?new Response('unavailable',{status:500}):Response.json(c.data);}return new Response('unknown',{status:404});};}
test('Andre faktiske Byggmax-kontroll oppdaterer samme SKU/butikk uten duplikater; butikkfeil sperrer bare den butikkens gamle pris',async()=>{const at=Date.parse(bm.checked_at),queue={parser_version:7,urls:bm.samples.map(s=>({url:s.url,chain:'byggmax'})),last_discovery:{byggmax:{finished_at:bm.checked_at}}};const first=await syncPublicPrices({queue,fetcher:bmFetcher(),clock:()=>at,pause:async()=>{},maxProducts:8});assert.equal(first.catalog.offers.length,7);assert.equal(first.catalog.stores.length,2);const second=await syncPublicPrices({previous:first.catalog,queue:first.queue,fetcher:bmFetcher(),clock:()=>at+21600001,pause:async()=>{},maxProducts:8});assert.equal(second.catalog.offers.length,7);assert.equal(second.catalog.price_history.length,7);assert.equal(second.catalog.job_history.length,2);assert(second.catalog.offers[0].checked_at>first.catalog.offers[0].checked_at);const failed=await syncPublicPrices({previous:second.catalog,queue:second.queue,fetcher:bmFetcher(true),clock:()=>at+43200002,pause:async()=>{},maxProducts:8});for(const o of failed.catalog.offers){const old=second.catalog.offers.find(p=>p.id===o.id);assert.equal(o.original_ore,old.original_ore);if(o.store_id==='2327'){assert(o.last_error);assert.equal(o.checked_at,old.checked_at);}else{assert(!o.last_error);assert(o.checked_at>old.checked_at);}}});
