import {validatePrices,applyPrices} from '../kalkyle-prices.js';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {publicSources,sourceUrl,retailerTaxEvidence,readPublicProducts,robotsPolicy,sitemapLinks,readPublicProduct,usableOffer,selectedPrices,offersForRow,materialPriority} from '../market-public-core.js';
import {syncPublicPrices} from '../scripts/sync-public-prices.mjs';
const source=publicSources[0],url=source.origin+'/trelast/sloyfer/1234567',now='2026-10-06T12:00:00.000Z';
const product={'@type':'Product',sku:'fixture',name:'Sløyfe 23x48 gran',url,offers:{'@type':'Offer',url,price:'25',priceCurrency:'NOK',availability:'https://schema.org/InStock',priceSpecification:{'@type':'UnitPriceSpecification',price:'25',priceCurrency:'NOK',valueAddedTaxIncluded:true,referenceQuantity:{value:1,unitCode:'MTR'}}}};
const html=(p=product,extra='')=>'<script type="application/ld+json">'+JSON.stringify(p)+'</script>'+extra;
test('Eksakt leverandøradresse, sitemaps og bread-and-butter-prioritet',()=>{assert.throws(()=>sourceUrl('https://www.obsbygg.no.evil.test/a',source));assert.throws(()=>sourceUrl('http://www.obsbygg.no/a',source));assert.deepEqual(sitemapLinks('<urlset><url><loc>https://www.obsbygg.no/a?x=1&amp;y=2</loc></url></urlset>').urls,['https://www.obsbygg.no/a?x=1&y=2']);assert(materialPriority('/sloyfer-23x48')>0);});
test('Robots bruker spesifikk agent, lengste regel, Allow ved likhet og query',()=>{const p=robotsPolicy('User-agent: *\nDisallow: /\nUser-agent: RIGOR\nDisallow: /private\nAllow: /private/public\nDisallow: /*?store=\nCrawl-delay: 4');assert(p.allows(source.origin+'/trelast'));assert(!p.allows(source.origin+'/private/a'));assert(p.allows(source.origin+'/private/public/a'));assert(!p.allows(source.origin+'/a?store=42'));assert.equal(p.delay,4);});
test('NOK, MVA, referansemengde, lager og produkt-ID leses fra kilden',()=>{const o=readPublicProduct(html(),url,source,now);assert.equal(o.normalized_ore,2000);assert.equal(o.package_quantity,1);assert.equal(o.kind,'battens');assert.equal(o.source_id,'fixture');assert(usableOffer(o,Date.parse(now)));const ps={...product.offers.priceSpecification,referenceQuantity:{value:4.8,unitCode:'MTR'}};assert.equal(readPublicProduct(html({...product,offers:{...product.offers,priceSpecification:ps}}),url,source,now).normalized_ore,417);});
test('Synlig pris/enhet krever samme prisverdi og entydig MVA; m² fungerer',()=>{const p={...product,name:'Isolasjon 100 mm',offers:{...product.offers,price:600,priceSpecification:undefined}};assert.equal(readPublicProduct(html(p,'<p>600,00 kr/m² inkl. mva</p>'),url,source,now).unit,'m2');assert.throws(()=>readPublicProduct(html(p,'<p>599,00 kr/m² inkl. mva</p>'),url,source,now));assert.throws(()=>readPublicProduct(html(p,'<p>600 kr/m²</p>'),url,source,now));assert.throws(()=>readPublicProduct(html(p,'<p>Medlemspris 600 kr/m² inkl. mva</p>'),url,source,now));});
test('Ukjent/lokal/fra-pris/produktliste eller utløpt pris kan ikke brukes',()=>{for(const patch of [{priceCurrency:'EUR'},{availableAtOrFrom:'local'},{eligibleCustomerType:'member'},{availability:'unknown'},{priceValidUntil:'2026-10-05'},{'@type':'AggregateOffer'}])assert.throws(()=>readPublicProduct(html({...product,offers:{...product.offers,...patch}}),url,source,now));assert.throws(()=>readPublicProduct(html([product,product]),url,source,now));const o=readPublicProduct(html(),url,source,now);assert(!usableOffer({...o,last_error:'HTTP 403'},Date.parse(now)));assert(!usableOffer(o,Date.parse(now)+25*3600000));});
test('Priser brukes først ved eksplisitt produktvalg og riktig materialtype/enhet',()=>{const o=readPublicProduct(html(),url,source,now),r={priceKey:'roof.underlay.sloyfer',materialUnit:'m',name:'Montere sløyfer'};assert.equal(selectedPrices([o],{},Date.parse(now)).length,0);assert.equal(selectedPrices([o],{[r.priceKey]:o.id},Date.parse(now))[0].pris,20);assert.equal(offersForRow(r,[o],Date.parse(now)).length,1);assert.equal(offersForRow({...r,materialUnit:'m²'},[o],Date.parse(now)).length,0);});
function fixtureFetch(fail=false,price=25){const calls=[];const fn=async(u,opts)=>{calls.push(u);assert.equal(opts.redirect,'error');if(u===source.vat_policy_url)return new Response('Alle priser er inkludert merverdiavgift.');if(u.endsWith('/robots.txt'))return new Response('User-agent: *\nAllow: /\nSitemap: '+source.origin+'/sitemap.xml');if(u===source.origin+'/sitemap.xml')return new Response('<urlset><url><loc>'+url+'</loc></url><url><loc>https://evil.test/isolasjon</loc></url></urlset>');if(u===url)return fail?new Response('blocked',{status:403}):new Response(html({...product,offers:{...product.offers,price,priceSpecification:{...product.offers.priceSpecification,price}}}));return new Response('blocked',{status:403});};return {fn,calls};}
test('Innhentingsjobb oppdager produkter, bruker ikke AI og stopper ved kildeblokkering',async()=>{const f=fixtureFetch(),r=await syncPublicPrices({fetcher:f.fn,clock:()=>Date.parse(now),pause:async()=>{},maxProducts:2});assert.equal(r.catalog.offers.length,1);assert.equal(r.catalog.last_run.succeeded,1);assert(r.queue.urls.every(q=>q.url.startsWith(source.origin)));assert(!f.calls.some(u=>u.includes('openai')));});
test('Feil bevarer forrige pris og kontrolltid, men sperrer prisen; store hopp flagges',async()=>{const o=readPublicProduct(html(),url,source,now);for(const f of [fixtureFetch(true),fixtureFetch(false,100)]){const r=await syncPublicPrices({previous:{offers:[o]},queue:{urls:[{url,chain:'obs',priority:90}],last_discovery:{obs:now}},fetcher:f.fn,clock:()=>Date.parse(now)+1000,pause:async()=>{},maxProducts:2});assert.equal(r.catalog.offers[0].normalized_ore,o.normalized_ore);assert.equal(r.catalog.offers[0].checked_at,now);assert(r.catalog.offers[0].last_error);assert.equal(r.catalog.last_run.failed,1);}});
test('Oppdagelse fortsetter neste sitemap ved puljegrensen',async()=>{const maps=[source.origin+'/a.xml',source.origin+'/b.xml'];const fetcher=async u=>new Response(u===source.vat_policy_url?'Alle priser er inkludert merverdiavgift.':u.endsWith('robots.txt')?'Sitemap: '+maps[0]+'\nSitemap: '+maps[1]:'<urlset></urlset>');const first=await syncPublicPrices({fetcher,clock:()=>Date.parse(now),pause:async()=>{},maxSitemaps:1,maxProducts:0});assert.deepEqual(first.queue.last_discovery.obs.pending,[maps[1]]);const second=await syncPublicPrices({queue:first.queue,fetcher,clock:()=>Date.parse(now),pause:async()=>{},maxSitemaps:1,maxProducts:0});assert.deepEqual(second.queue.last_discovery.obs.pending,[]);});

test('Isolasjonstykkelse som er oppgitt i posten kan ikke byttes til en annen',()=>{const o=readPublicProduct(html({...product,name:'Isolasjon 100 mm',offers:{...product.offers,priceSpecification:{...product.offers.priceSpecification,referenceQuantity:{value:1,unitCode:'MTK'}}}}),url,source,now);assert.equal(offersForRow({priceKey:'insulation.isolasjon100',name:'Montere 100 mm isolasjon',materialUnit:'m²'},[o,{...o,id:'150',name:'Isolasjon 150 mm'}],Date.parse(now)).length,1);});

test('Vanlige schema-URI-er og WebPage.mainEntity støttes uten å bruke relaterte produkter',()=>{const p={...product,'@type':'https://schema.org/Product',offers:{...product.offers,'@type':'https://schema.org/Offer'}};assert.equal(readPublicProduct(html({'@type':'WebPage',mainEntity:p}).replace('type=','type = '),url,source,now).normalized_ore,2000);});

test('Dokumenterte varer blir kontrollert før ukjente adresser når budsjettet er lite',async()=>{const o=readPublicProduct(html(),url,source,now),f=fixtureFetch();const r=await syncPublicPrices({previous:{offers:[o]},queue:{urls:[{url:source.origin+'/isolasjon/isolasjon-ukjent/2345678',chain:'obs',priority:100},{url,chain:'obs',priority:95,last_attempt_at:'2026-10-05T00:00:00Z'}],last_discovery:{obs:now}},fetcher:f.fn,clock:()=>Date.parse(now)+1000,pause:async()=>{},maxProducts:2});assert.equal(r.catalog.last_run.succeeded,1);assert(!f.calls.includes(source.origin+'/isolasjon/isolasjon-ukjent/2345678'));});

test('Prisreferanse behandles ikke som fysisk pakningsinnhold eller hele bord',()=>{const at=new Date().toISOString(),o=readPublicProduct(html(),url,source,at),prices=validatePrices(selectedPrices([o],{test:o.id}));const row={priceKey:'test',materialUnit:'m',materialQuantity:4.2,quantity:4.2};const r=applyPrices([row],'market',prices,at.slice(0,10))[0];assert.equal(r.marketMaterialCost,undefined);assert.equal(r.marketPackages,undefined);assert.equal(r.material,20);assert(r.priceSource.includes('pakningsavrunding'));});

test('Obs ProductGroup bindes til én variant eller en eksplisitt valgt variant-URL',()=>{const variant={...product,url:url+'?v=fixture',offers:{...product.offers,url:url+'?v=fixture'}};const group={'@type':'ProductGroup',url,hasVariant:[variant]};assert.equal(readPublicProduct(html(group),url,source,now).url,variant.url);const other={...variant,sku:'other',url:url+'?v=other',offers:{...variant.offers,url:url+'?v=other'}};assert.throws(()=>readPublicProduct(html({...group,hasVariant:[variant,other]}),url,source,now));assert.equal(readPublicProduct(html({...group,hasVariant:[variant,other]}),variant.url,source,now).source_id,'fixture');});

test('Obs-variant med dokumentert pakningsareal og verifisert avgiftsvilkår får riktig pris per m²',()=>{const tax=retailerTaxEvidence('Alle priser er inkludert merverdiavgift.',source.vat_policy_url,source,now);const variant={...product,name:'Trefiberisolasjon',size:'100 MM',url:url+'?v=fixture',offers:{...product.offers,url:url+'?v=fixture',price:489,priceSpecification:undefined}};const group={'@type':'ProductGroup',url,hasVariant:[variant]};const offer=readPublicProducts(html(group,'100 mm, leveres i pakker á 2,8 m²'),url,{...source,tax_evidence:tax},now)[0];assert.equal(offer.normalized_ore,13971);assert.equal(offer.package_quantity,2.8);assert.equal(offer.quantity_basis,'package');assert.equal(offer.original_unit,'pakke');assert.throws(()=>readPublicProducts(html(group,'100 mm, leveres i pakker á 2,8 m²'),url,source,now));});
