import {test} from 'node:test';import assert from 'node:assert/strict';
const env={SUPABASE_URL:'https://fixture.invalid',SUPABASE_SERVICE_ROLE_KEY:'fixture-service',RIGOR_PRICE_JOB_KEY:'fixture-job'};
let handler;globalThis.Deno={env:{get:k=>env[k]},serve:f=>handler=f};
await import('../supabase/functions/rigor-market-prices/index.ts');
const originals=globalThis.fetch;const json=v=>new Response(JSON.stringify(v),{headers:{'Content-Type':'application/json'}});
const request=(action,token='admin',extra={})=>handler(new Request('https://function.invalid',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action,...extra})}));
let calls=[],lastError,lastSuccess,nextCheck,observations=[];const product={id:'p',group_id:'g',chain:'obs',source_id:'123',name:'Testfixture',url:'https://www.obsbygg.no/testfixture',unit:'m2',vat:'inkl',price_kind:'ordinary',package_quantity:6,enabled:true,approved:true};
function mock({role='admin',active=true,failure=false,running=false,old=null}={}){calls=[];lastError=null;lastSuccess=null;observations=[];globalThis.fetch=async(url,init={})=>{calls.push({url:String(url),init});const path=String(url);if(path.includes('/auth/v1/user'))return init.headers.Authorization==='Bearer invalid'?new Response('',{status:401}):json({id:'user'});if(path.includes('portal_users'))return json([{role,active}]);if(path.includes('rigor_current_price_observations'))return json([]);if(path.includes('claim_rigor_price_job'))return json(running?null:'job');if(path.includes('rigor_price_sources'))return json(init.method==='PATCH'?[]:[{chain:'obs',enabled:true,permitted:true,interval_hours:6}]);if(path.includes('rigor_price_groups'))return json([{id:'g',unit:'m2',kind:'insulation',specs:{thickness:100,lambda:.035,application:'vegg',material:'mineralull'}}]);if(path.includes('rigor_price_products')){if(init.method==='PATCH'){const body=JSON.parse(init.body);lastError=body.last_error;lastSuccess=body.last_success_at;nextCheck=body.next_check_at;return json([]);}return json([product]);}if(path.includes('rigor_price_observations')){if(init.method==='POST'){observations.push(JSON.parse(init.body));return json([]);}return json(old?[old]:[]);}if(path.includes('rigor_price_jobs'))return json([]);if(path.endsWith('/robots.txt'))return new Response('User-agent: *\nAllow: /');if(path===product.url){if(failure)return new Response('',{status:403});return new Response('<script type="application/ld+json">'+JSON.stringify({'@type':'Product',sku:'123',offers:{'@type':'Offer',price:600,priceCurrency:'NOK',availability:'https://schema.org/InStock'}})+'</script>');}throw Error('Uventet fixture-kall '+path);};}
test('Innlogging og aktiv konto kreves, og medlem kan ikke administrere',async()=>{mock();assert.equal((await request('admin','invalid')).status,401);mock({active:false});assert.equal((await request('admin')).status,401);mock({role:'member'});assert.equal((await request('sync')).status,403);assert(!calls.some(c=>c.url.includes('claim_rigor')));});
test('Scheduler krever riktig egen hemmelighet og sjekker duplikatvern',async()=>{mock({running:true});const r=await request('sync','fixture-job');assert.equal((await r.json()).status,'already_running_or_recent');assert(!calls.some(c=>c.url.includes('/auth/')));});
test('Fixture-innhenting lagrer originalpris, omregning og kontrolltid',async()=>{mock();const r=await request('sync');assert.equal((await r.json()).succeeded,1);assert.equal(observations.length,1);assert.equal(observations[0].original_ore,60000);assert.equal(observations[0].normalized_ore,8000);assert(observations[0].accepted);assert(lastSuccess);});
test('Kildefeil bevarer siste pris og vellykkede kontrolltid',async()=>{mock({failure:true});const r=await request('sync');assert.equal((await r.json()).failed,1);assert.equal(observations.length,0);assert.equal(lastSuccess,undefined);assert.match(lastError,/403/);});
test('Mistenkelig prisendring flagges uten å overta gyldig pris',async()=>{mock({old:{normalized_ore:1000}});await request('sync');assert.equal(observations[0].accepted,false);assert.equal(lastSuccess,undefined);assert.match(lastError,/flagget/);});
test('Manglende produktspesifikasjoner kan ikke godkjennes',async()=>{mock();const r=await request('product','admin',{product:{...product,original_unit:'pakke',specs:{thickness:100},approval_note:'Fixture'}});assert.equal(r.status,400);assert.match((await r.json()).error,/spesifikasjoner/);});
process.on('exit',()=>globalThis.fetch=originals);

test('Forfalte varer hentes i puljer og får separat neste kontrolltid',async()=>{mock();await request('sync','fixture-job');assert(calls.some(c=>c.url.includes('next_check_at.lte.')));assert(Math.abs(Date.parse(nextCheck)-Date.now()-6*3600000)<5000);mock({failure:true});await request('sync','fixture-job');assert(Math.abs(Date.parse(nextCheck)-Date.now()-3600000)<5000);});

test('Katalog bruker paginert register og én aktuell observasjon per produkt',async()=>{mock();const r=await request('catalog');assert.equal(r.status,200);assert(calls.some(c=>c.url.includes('rpc/rigor_current_price_observations?limit=1000&offset=0')));});
